Anime
uclaacm/Playnet pull request #109
Opened 2021-04-08 19:13 UTC by reginawang99

2021-04-09 03:52 UTC, BryanPan342 requested changes
LGTM, i had some general comments

2021-04-09 03:52 UTC, BryanPan342 commented on src/components/shared/ScalingSlide.tsx
> +  };
I would prefer if this is in css

2021-04-09 03:52 UTC, BryanPan342 commented on src/components/Activities/Activity3/Animations/ManyEmployees.tsx
> +    timeline.current?.add({
```suggestion
    })
    .add({
```

2021-04-09 04:35 UTC, reginawang99 commented on src/components/shared/ScalingSlide.tsx
> +  };
mmhm i agree! i was looking into it and since `height` and `width` are props, I couldn't find a good way to set the scss variables based on the input `height` and `width` where the two are css variables
eg https://stackoverflow.com/a/53442696 
thoughts?

2021-04-09 05:19 UTC, BryanPan342 commented on src/components/shared/ScalingSlide.tsx
> +  };
we could put it as a css variable in HTML?

like --weight --height

2021-04-09 19:28 UTC, reginawang99 commented on src/components/styles/ScalingSlide.scss
> +  /** this is basically what we need--is this even possible? **/
:(

2021-04-09 21:44 UTC, BryanPan342 commented on src/components/styles/ScalingSlide.scss
> +  /** this is basically what we need--is this even possible? **/
Check out this code snippet!

https://github.com/BryanPan342/bryan.pan/blob/e53c3778dc52f345ff06e306a617d4b2d84674ef/src/utils/hooks.ts#L17-L20

https://github.com/BryanPan342/bryan.pan/blob/e53c3778dc52f345ff06e306a617d4b2d84674ef/src/components/styles/_variables.scss#L20


This is how I would use the scss styles that can get updated programatically

2021-04-10 00:47 UTC, reginawang99 commented on src/components/styles/ScalingSlide.scss
> +  /** this is basically what we need--is this even possible? **/
should i use this over the `const cssProperties: any = {};` that I'm currently using?

2021-04-10 18:59 UTC, reginawang99 commented on src/components/shared/ScalingSlide.tsx
> +    const animationScale = scaling * (contentSize / animationWidth);
we can also theoretically put this in the scss file if you think it makes it cleaner. personally, i think placing the logic out here makes sense to me!

2021-04-10 21:38 UTC, BryanPan342 approved these changes
LGTM

2021-04-10 21:38 UTC, merged