Create Slides 3 4
uclaacm/Playnet pull request #124
Opened 2021-04-14 05:24 UTC by Phreakester

Closes #99

2021-04-14 21:19 UTC, BryanPan342 requested changes
would like to reduce some code duplication and not sure about prop.start

2021-04-14 21:19 UTC, BryanPan342 commented on src/components/Activities/Activity3/Animations/ManyEmployees.tsx
> +  }, [reloadTime, props.start, slideIdx]);
is props.start still needed?

if so, we should have a check to see if start is true to start playing and if not then we should pause and clear our timeout!

2021-04-16 03:54 UTC, Phreakester commented on src/components/Activities/Activity3/Animations/ManyEmployees.tsx
> +      duration: 1000,
Oh, so it kinda appends that to the end of the object? Seems very useful, thank you!

2021-04-16 04:12 UTC, Phreakester commented on src/components/Activities/Activity3/Animations/ManyEmployees.tsx
> +  }, [reloadTime, props.start, slideIdx]);
Hmmm, I believe so as the first slide doesnt have an animation so we dont want to start playing until after.

2021-04-16 04:13 UTC, Phreakester commented on src/components/Activities/Activity3/Animations/ManyEmployees.tsx
> +  }, [reloadTime, props.start, slideIdx]);
Unless you see a better way to stop just the first slide from playing?

2021-04-16 18:44 UTC, BryanPan342 commented on src/components/Activities/Activity3/Animations/ManyEmployees.tsx
> +  }, [reloadTime, props.start, slideIdx]);
If it's just the first slide I say we just check if slideIdx is 0?

2021-04-16 19:18 UTC, BryanPan342 approved these changes
LGTM

2021-04-16 19:19 UTC, merged