feat: activity3 game wrapper
uclaacm/Playnet pull request #125
Opened 2021-04-15 03:08 UTC by reginawang99

closes #110

2021-04-15 15:56 UTC, BryanPan342 requested changes
some really impressive logic going on here!

had a couple of nits and unsure about the need for the useStateCallback.. kinda need an explanation on why we need the custom hook and not just write our own callback?

2021-04-15 15:56 UTC, BryanPan342 commented on src/components/Activities/Activity3/Game/PriorityChoices.tsx
> +function GameWrapper(): JSX.Element {
Let's change this to PriorityChoices?

2021-04-15 15:56 UTC, BryanPan342 commented on src/components/Activities/Activity3/Game/index.tsx
> +    const curSkipStates = tempSkipStates ? tempSkipStates : [A3_GAME_STATE.EmptyState];
```suggestion
    const curSkipStates = tempSkipStates ?? [A3_GAME_STATE.EmptyState];
```

2021-04-15 15:56 UTC, BryanPan342 commented on src/components/shared/hooks.ts
> +export function useStateCallback<T>(initialState: T | (() => T)): [T, DispatchWithCallback<SetStateAction<T>>] {
why do we need this?

2021-04-15 15:56 UTC, BryanPan342 commented on src/components/Activities/Activity3/Game/GameConstants.tsx
> +const NEXT_STATE_MAP = new Map<A3_GAME_STATE, A3_GAME_STATE[]>();
nit: usually we have been using objects for this

```
const NEXT_STATE_MAP: {[key: A3_GAME_STATE]: A3_GAME_STATE[]} = {};
```

2021-04-15 15:56 UTC, BryanPan342 commented on src/components/Activities/Activity3/Game/GameConstants.tsx
> +const NEXT_STATE_MAP = new Map<A3_GAME_STATE, A3_GAME_STATE[]>();
we can also right this out as a constant!


```ts
const NEXT_STATE_MAP = STATE_ORDERING_LIST.reduce((ret, state, index) => {
  return {...ret, [state]: getNextStates(index)};
}, {});
```

2021-04-15 15:56 UTC, BryanPan342 commented on src/components/Activities/Activity3/Game/PriorityChoices.tsx
> +            <VariableCard id={variable} key={variable} />,
is the Variable_Positioning varaible really needed? 

esp if the css style is handling its position anyways?

2021-04-15 19:57 UTC, reginawang99 commented on src/components/shared/hooks.ts
> +export function useStateCallback<T>(initialState: T | (() => T)): [T, DispatchWithCallback<SetStateAction<T>>] {
i think cuz we want to make sure that all `useEffect` of `setStatesToSkip` finish first before the callback happens. This is because the first `setState` needs to have the `statesToSkip` saved. 

I think from what i know, the callback doesn't wait for all states to be saved/`useEffect`s to be run before calling the callback? im not super good with react lifecycle tho, so i could be wrong, i defs had to finnick with this to throw something together 😅

2021-04-16 03:11 UTC, BryanPan342 approved these changes
LGTM

2021-04-16 03:12 UTC, merged