feat: select and save varaibles
uclaacm/Playnet pull request #126
Opened 2021-04-15 06:09 UTC by reginawang99

unblocks #112

2021-04-16 06:43 UTC, darren2hang reviewed
This looks really good! I have a one question though. Why did you decide to use a switch statement instead of a dictionary/hashmap? My intuition tells the dictionary would have faster runtime, but I don't think it matters much in this case, since the map is only like 6 long.

2021-04-16 07:19 UTC, reginawang99 commented
oooo good point, in my brain, the switch statement is easier to read (cuz mapping + return value in one area)! tbh im down for either and am down to change, but am v curious as to what @BryanPan342 thinks also

2021-04-16 19:04 UTC, BryanPan342 requested changes
minor nit

2021-04-16 19:04 UTC, BryanPan342 commented on src/components/Activities/Activity3/Game/index.tsx
> +}>>({});
make the Partial an interface!

```
interface IGameContext {
  setState: (state: A3_GAME_STATE) => void,
  goNextState: () => void,
  variableSelection: VARIABLES[],
}
```

2021-04-17 00:10 UTC, BryanPan342 approved these changes
LGTM

2021-04-17 00:11 UTC, merged