feat: slide 10 of A3, sliding list
uclaacm/Playnet pull request #131
Opened 2021-04-16 08:15 UTC by reginawang99

closes #102

2021-04-16 19:01 UTC, BryanPan342 requested changes
minor change

2021-04-16 19:01 UTC, BryanPan342 commented on src/components/Activities/Activity3/Animations/List.tsx
> +  const MAPPED_PARAMETERS = RECOMMENDATION_PARAMETERS.map((element) => <><p/>{element}</>);
should this just be a <p> tag?

2021-04-16 19:47 UTC, reginawang99 commented
lint complains `  38:72  error  Missing "key" prop for element in iterator  react/jsx-key` 
hope it doesnt matter :-0

2021-04-17 00:11 UTC, BryanPan342 approved these changes
LGTM

2021-04-17 00:12 UTC, merged