feat: Select number days for each part of project
uclaacm/Playnet pull request #137
Opened 2021-04-17 19:36 UTC by tr89on

select days/add # days to context

closes #129

2021-04-17 22:22 UTC, darren2hang requested changes
A few minor changes. Feel free to not add the scrolling feature if you don't want to. Also, maybe ask Regina about storing the # of days for each task.

2021-04-17 22:22 UTC, darren2hang commented on src/components/Activities/Activity3/Game/NumberSelection.tsx
> +    <input type='number' value={input} onChange={handleChange} onClick={(e : any)=>e.target.select()} className={'time-input'}/>
would be cool if you add the ability to scroll the days also.
add a "onWheel={handleScroll}"

2021-04-17 22:22 UTC, darren2hang commented on src/components/Activities/Activity3/Game/NumberSelection.tsx
> +
```suggestion
const handleScroll = (e: React.WheelEvent) => {
  let adjustment = 0;
  if (e.deltaY < 0) {
    adjustment = -1;
  } else if (e.deltaY > 0 ) {
    adjustment = 1;
  }
  const newInput = Math.max(Math.min(input + adjustment, daysLeft), 0);
  setInput(newInput);
  setDaysUsed(newInput);
}
```

2021-04-17 22:22 UTC, darren2hang commented on src/components/Activities/Activity3/Game/NumberSelection.tsx
> +    <input type='number' value={input} onChange={handleChange} onClick={(e : any)=>e.target.select()} className={'time-input'}/>
```suggestion
    <input type='number' value={input} onChange={handleChange} onWheel={handleScroll} onClick={(e : any)=>e.target.select()} className={'time-input'}/>
```

2021-04-17 22:22 UTC, darren2hang commented on src/components/Activities/Activity3/Game/index.tsx
> +  setDaysLeft: (state: number) => void,
should there also be an array or something to store the number of days dedicated to each task?

2021-04-17 22:22 UTC, darren2hang commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +  const [testDays, setTestDays] = useState<number>(0);
don't think you need the <number> in the useState since Typescript figures out the type from the hook, but it doesn't hurt.

2021-04-18 02:34 UTC, reginawang99 commented
ya can you store number days in the context, ill pr after you resolve darrens review

2021-04-18 03:45 UTC, tr89on commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +  const [testDays, setTestDays] = useState<number>(0);
good to know!

2021-04-18 06:12 UTC, reginawang99 reviewed
oop ill finish looking at your pr after you add this?
default start with 7*8 day = 56 days

between 14-21 day good: https://www.figma.com/file/7DzNiScbp6t3x0p86pz5P9/Playnets?node-id=2150%3A78004
over 21 days: https://www.figma.com/file/7DzNiScbp6t3x0p86pz5P9/Playnets?node-id=1799%3A77180

2021-04-18 06:12 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +  const [testDays, setTestDays] = useState(initialTasks[ABTEST] ?  initialTasks[ABTEST] : 0);
can we do this in a useEffect onMount?

2021-04-18 07:37 UTC, tr89on commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +  const [testDays, setTestDays] = useState(initialTasks[ABTEST] ?  initialTasks[ABTEST] : 0);
I tried using useEffect but it doesn't seem to update during the initial render so everything starts out at 0 😵

2021-04-18 09:52 UTC, reginawang99 requested changes
🥞 just some \~clean up\~ looks 🍗

2021-04-18 09:52 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/index.tsx
> +  taskSelection: number[],
can we call the variable something like `timeAllocation` or `daysAllocation` or something else? `taskSelection` seems like the same as `variableSelection` and I probably wouldn't know the difference if i was just glancing at the code base!

feel free to change the `A3_GAME_STATE.TimeAllocation` enum name also!

2021-04-18 09:52 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/index.tsx
> +      : [0,0,0];
`object?.command()` --> object runs command if object is not null!
`object ?? [value]` --> returns `[value]` if object is null  
```suggestion
    const tempTasks : number[] = storedTasks?.split(',').map((elem) => {
        // elem can be either '' or a number
        return (elem && elem.length > 0) ? parseInt(elem) : 0;
      })
      ?? [0,0,0];
```

2021-04-18 09:52 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/index.tsx
>        storage.removeItem(SESSION_VARIABLES);
let's remove with everyone else!
```suggestion
      storage.removeItem(SESSION_VARIABLES);
      storage.removeItem(SESSION_TASKS);
```

2021-04-18 09:52 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +      </div>
let change this to a
```map(()=>{
<div className={'centered-box'}>
        <img src={src}/>
        {text}
      </div>
```
function and define a map of `src` and `text` somewhere! (to reduce code) 🥘

2021-04-18 09:52 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +      </div>
lets change this to another `map` as well! you'll probably want to do the state variable change first! 🇭🇺

2021-04-18 09:52 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +  };
(or put into area directly!)
```suggestion
  const handleGoNext = () => {
    goNextState && goNextState();
  };
```

2021-04-18 09:52 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +
lets update `daysleft` when the other 3 change! this is so that on refresh or going back, things will save! also cuz reduce this complexity elsewhere 🥧 
```suggestion
  useEffect(() =>{
    setDaysLeft && setDaysLeft(daysLeft ? (daysLeft - buildDays - debugDays - testDays) : 0);
    setTaskSelection([buildDays, debugDays, testDays]);
  }, [buildDays, debugDays, testDays]);
```

2021-04-18 09:52 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +  }, []);
figure out the weird state onmount stuff for you! 
```suggestion
  const [buildDays, setBuildDays] = useState(0);
  const [debugDays, setDebugDays] = useState(0);
  const [testDays, setTestDays] = useState(0);

  useEffect(() => {
    const initBuildDays = initialTasks[BUILD] ?? 0;
    const initDebugDays = initialTasks[DEBUG] ?? 0;
    const initABTestDays = initialTasks[ABTEST] ?? 0;
    setBuildDays(initBuildDays);
    setDebugDays(initDebugDays);
    setTestDays(initABTestDays);
  }, []);
```

2021-04-18 09:52 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +  const [testDays, setTestDays] = useState(() => initAllocation(ABTEST));
for the second map function, you probably want to change this to a singular state variable! i can help you with that if you want 🍕 
(or just directly use `setTaskSelection` and `initialTasks` if that works, which it should)

2021-04-18 09:52 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +  }, []);
see below about `??`

2021-04-18 09:52 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/NumberSelection.tsx
> +  const [input, setInput] = useState(daysUsed);
we can actually just use `setDaysUsed` and `daysUsed`, no state variable needed 😋 
```suggestion
```

2021-04-18 09:52 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/NumberSelection.tsx
> +      value={input}
```suggestion
      value={daysUsed}
```

2021-04-18 09:52 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/GameConstants.tsx
> +  ABTEST = 2,
no need to change: 0, 1, 2 are already default btw, just a thing 🧇 

https://www.typescriptlang.org/docs/handbook/enums.html

> If we wanted, we could leave off the initializers entirely:
>
> enum Direction {
>   Up,
>   Down,
>   Left,
>   Right,
> }
> Here, Up would have the value 0, Down would have 1, etc. This auto-incrementing behavior is useful for cases where we might not care about the member values themselves, but do care that each value is distinct from other values in the same enum.

2021-04-18 20:20 UTC, tr89on commented on src/components/Activities/Activity3/Game/index.tsx
> +      : [0,0,0];
oh good to know!

2021-04-18 20:31 UTC, tr89on commented on src/components/Activities/Activity3/Game/GameConstants.tsx
> +  ABTEST = 2,
oh cool good to know!

2021-04-19 00:36 UTC, reginawang99 reviewed
honestly, id just approve, but you need to resolve changes to `main` anyways

feel free to dismiss all of this

2021-04-19 00:36 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/GameConstants.tsx
> +
```suggestion

// Time Allocation Info
```

2021-04-19 00:36 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +  const displayWarning = () => {
more clear that this return JSX Element, and that it doesn't cause a display of warning
```suggestion
  const getDisplayWarning = (): JSX.Element => {
```

2021-04-19 00:36 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +  const showWarning = () => {
maybe `isShowWarning` for more clear boolean result or something idk

2021-04-19 00:36 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +
```suggestion
```

2021-04-19 00:36 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +
```suggestion
```

2021-04-19 00:39 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +    return;
```suggestion
    return <></>;
```

2021-04-19 01:24 UTC, reginawang99 approved these changes
LGTM

2021-04-19 01:25 UTC, merged