feat: slides 16-19
uclaacm/Playnet pull request #138
Opened 2021-04-17 21:37 UTC by tr89on

debugging animation

closes #105

2021-04-17 21:59 UTC, darren2hang requested changes
Small change, but otherwise looks good! I think your use of defining fadeIn and fadeOut objects to avoid having to retype was pretty smart!

2021-04-17 21:59 UTC, darren2hang commented on src/components/Activities/Activity3/Animations/Debugging.tsx
> +    if (slideIdx === 7) { //As there is no animation for slide 1
maybe instead of calculating which animation to run based on the slideIdx of carousel, you could have Debugging take in an index as props. And then have decide the animation based on the props instead of the carousel id. I feel like a prop allows for the component to be more reusable.

2021-04-17 22:01 UTC, tr89on commented on src/components/Activities/Activity3/Animations/Debugging.tsx
> +    if (slideIdx === 7) { //As there is no animation for slide 1
Oh yea that makes sense!

2021-04-18 02:39 UTC, darren2hang approved these changes
Looks good!

2021-04-18 02:40 UTC, merged