feat: graphing util untested
uclaacm/Playnet pull request #149
Opened 2021-04-19 10:40 UTC by reginawang99

closes #136

2021-04-19 16:37 UTC, BryanPan342 requested changes
i didnt really look into the logic for the functions, but I like the way the return structure is working

if we could just add a single sentence describing the function similar in spirit to the cipher stuff that would be awesome

https://github.com/uclaacm/Playnet/blob/4334c0312940a0229ba10b310c6b9887077eb9b5/src/utils/cipher.ts#L17-L22

2021-04-19 16:37 UTC, BryanPan342 commented on src/utils/numbers.ts
> +export function squeeze(num: number, min: number, max: number) : [number, number]{
the general term for this is clamp!

2021-04-19 16:37 UTC, BryanPan342 commented on src/utils/numbers.ts
> +export function squeeze(num: number, min: number, max: number) : [number, number]{
```suggestion
export function clamp(min: number, num: number, max: number) : [number, number]{
```

2021-04-19 16:37 UTC, BryanPan342 commented on src/utils/numbers.ts
> + */
```suggestion
/**
 * Given a number and its min and max range, return either the number or the edges of the range.
 *
 * @returns [result, difference]
 * @var result: the clamped value
 * @var difference: the difference between the clamped value and the input num
 */
```

2021-04-19 16:37 UTC, BryanPan342 commented on src/components/Activities/Activity3/Game/GameConstantsToMessWith.ts
> +  'Warning: Function components cannot be given refs.', 'net::ERR_ABORTED 403 (Forbidden)', 'React version not specified',
LMAO what is this?

2021-04-19 16:37 UTC, BryanPan342 commented on src/components/Activities/Activity3/Game/gameCalculationsUtil.ts
>   * @returns points between x: [0, 100], y: [0, 100] to graph
if we could add a really general comment on how the function works that would be awesome!

2021-04-19 16:37 UTC, BryanPan342 commented on src/components/Activities/Activity3/Game/gameCalculationsUtil.ts
>  export function getControlGraphForABTesting(
if we could add a really general comment on how the function works that would be awesome!

2021-04-19 20:58 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/GameConstantsToMessWith.ts
> +  'Warning: Function components cannot be given refs.', 'net::ERR_ABORTED 403 (Forbidden)', 'React version not specified',
LOLLL debug screen ahaha 
![image](https://user-images.githubusercontent.com/29292203/115302372-37f42900-a117-11eb-8bb0-56d0baf0f3f7.png)

ive just been adding random bugs there ahaha

2021-04-19 21:06 UTC, BryanPan342 commented on src/components/Activities/Activity3/Game/GameConstantsToMessWith.ts
> +  'Warning: Function components cannot be given refs.', 'net::ERR_ABORTED 403 (Forbidden)', 'React version not specified',
ooo haha okay sounds good

2021-04-20 04:02 UTC, BryanPan342 approved these changes
Good enough for me!

2021-04-20 04:02 UTC, merged