fix: add timealloc tutorial selectors
uclaacm/Playnet pull request #150
Opened 2021-04-19 20:22 UTC by tr89on

highlight each option during tutorial

2021-04-19 23:32 UTC, reginawang99 requested changes
here are a few map changes + things i forgot to catch before! looks good so far :)

2021-04-19 23:32 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
>    return <div id={'time-container'} className={tutorialStage < TUTORIAL_END ? 'enable-blur' : ''}>
can we replace `tutorialStage < TUTORIAL_END ` with `isTutorial` throughout the code? oops for not catching before
```suggestion
  return <div id={'time-container'} className={isTutorial ? 'enable-blur' : ''}>
```

2021-04-19 23:32 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +    <div id={'time-tutorial-overlay'} className={'disable-blur'} style={{display: `${tutorialStage >= TUTORIAL_END ? 'none' : ''}`}}>
display none is a lil funny, lets use JSX~
```suggestion
    {
     isTutorial && <div id={'time-tutorial-overlay'} className={'disable-blur'}>```

2021-04-19 23:32 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +      }
since we are only showing one bubble at a time, we dont need to do display = none or mapping, let's do something like this isntead!
```suggestion

  return <div id={'time-container'} className={isTutorial ? 'enable-blur' : ''}>
    {
     isTutorial && <div id={'time-tutorial-overlay'} className={'disable-blur'}>
      <div id={'time-tutorial-bubble'}
        className={`${tutorialStyles[tutorialStage]} disable-blur`}>
        {displayTutorialText()}
        <button className='playnet-button' style={{zIndex: 50}} onClick={advanceTutorial}>Continue</button>
      </div>
```

2021-04-19 23:32 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +            className={`option-container ${tutorialStage !== TUTORIAL_END && (tutorialStage === index ? 'disable-blur highlight-border' : 'enable-blur')}`}>
can we replace tutorialStage < TUTORIAL_END with isTutorial throughout the code? oops for not catching before

2021-04-19 23:32 UTC, reginawang99 commented on src/components/styles/Activity3Game.scss
> +}
these might need to be chaged because of our changes!

2021-04-20 05:45 UTC, tr89on commented on src/components/styles/Activity3Game.scss
> +}
rip

2021-04-20 05:51 UTC, tr89on commented on src/components/styles/Activity3Game.scss
> +}
nvm figured it out

2021-04-20 06:35 UTC, reginawang99 requested changes
some more cleanup that i didnt notice before! mbmb

2021-04-20 06:35 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +  ));
let's move this down into the code! i see that you call `optionIcons[index]` so im wondering why not just have this directly in the code?
```suggestion
```

2021-04-20 06:35 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> -  return <div id={'time-container'} className={tutorialStage < TUTORIAL_END ? 'enable-blur' : ''}>
random cleanup, but can we have the `displayTutorialText` in a map?

2021-04-20 06:35 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +            {optionIcons[index]}
we can do this instead of optionIcons!
```suggestion
          <div key={DISPLAY_OPTIONS[index].text}
              className={'centered-box'}>
              <img src={DISPLAY_OPTIONS[index].src} />
              {DISPLAY_OPTIONS[index].text}
            </div>```

2021-04-20 06:35 UTC, reginawang99 commented on src/components/styles/Activity3Game.scss
> +  padding: 0 !important;
i can take a look at this later, but in the style guideline, i think `!important` is not recommended
https://github.com/uclaacm/Playnet/blob/main/DESIGN_GUIDELINES.md#styling

2021-04-21 04:58 UTC, tr89on commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> -  return <div id={'time-container'} className={tutorialStage < TUTORIAL_END ? 'enable-blur' : ''}>
wait how would that work?

2021-04-21 05:03 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> -  return <div id={'time-container'} className={tutorialStage < TUTORIAL_END ? 'enable-blur' : ''}>
Take a look at GameConstants! Near the bottom there should be a map to JSX elements

2021-04-21 17:25 UTC, reginawang99 approved these changes
LGTM

2021-04-22 00:44 UTC, reginawang99 approved these changes
LGTM

2021-04-22 00:45 UTC, merged