feat: selecting features tutorial (slide 25)
uclaacm/Playnet pull request #151
Opened 2021-04-20 05:33 UTC by darren2hang

- I'm not sure if using an array to map indeces from the variable card index to the feature explanations index is the best (look at line 9 and 20 of FeaturesTutorial.tsx)
- Maybe could have reused variable card in FeaturesTutorial but I think that would have required too much modification of variable card
- Let me know how the css looks
closes: #111

2021-04-20 06:45 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/FeaturesTutorial.tsx
> +    VARIABLES.SAME_CREATOR, VARIABLES.SAME_CONTENT, VARIABLES.SUBSCRIBED];
make a singular map for
`variableIndexToSlideIndex`
`descriptionNames`
`row`
`col`! it'd be easier if everything was in the same spot, and the `(parseInt((i) / 3) + 1)` stuff is a lil hard to read

2021-04-20 06:55 UTC, reginawang99 requested changes
wow this is really clean :0 just some minor changes!

2021-04-20 06:55 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/FeaturesTutorial.tsx
> +                  '--row': (parseInt((i) / 3) + 1),
maybe let's just inline style the `grid-column` and `grid-row`? i dont have strong opinions, its just that my vscode gets a lil angy at css variables, so id prefer it personally. but i dont think its important, so feel free to dismiss!

2021-04-20 06:55 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/FeaturesTutorial.tsx
> +  };
let's change this to useEffect w index because it's easier to see what's going on/less nested
```suggestion
    useEffect(() => {
    if (index >= descriptionNames.length){
      goNextState();
    }
  }, [index]);
```

2021-04-20 06:55 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/FeaturesTutorial.tsx
> +  };
oop
```suggestion
  const isMatchingIndex = (variableCardIndex: number) => {
    return index === variableIndexToSlideIndex[variableCardIndex];
  };
```

2021-04-20 06:55 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/InfoCard.tsx
> +  parentIndex: number,
i think we should just specify the index of the infoCard from the parent! in that map i recommended above

2021-04-20 06:55 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/InfoCard.tsx
> +        style={{ '--info-card-col': getCol() }}
specify `grid-column: getCol` instead!

2021-04-20 18:14 UTC, darren2hang commented on src/components/Activities/Activity3/Game/FeaturesTutorial.tsx
> +  };
this gives me out of bounds error now. Like it tries to render out of bounds array before the useEffect kicks in

2021-04-20 18:32 UTC, darren2hang commented on src/components/Activities/Activity3/Game/FeaturesTutorial.tsx
> +    VARIABLES.SAME_CREATOR, VARIABLES.SAME_CONTENT, VARIABLES.SUBSCRIBED];
I wasn't able to get rid of the i%3 +1 and parseInt(i/3) + 1 stuff

2021-04-20 18:33 UTC, darren2hang commented on src/components/Activities/Activity3/Game/InfoCard.tsx
> +  parentIndex: number,
I just made the column of the info card be passed in as a prop

2021-04-21 02:39 UTC, BryanPan342 approved these changes
LGTM

2021-04-21 02:43 UTC, merged