feat: remove debug + fix change priorities day req
uclaacm/Playnet pull request #194
Opened 2021-05-11 02:06 UTC by tr89on

-removes debug option for act 3 game
-sets default time allocation to 7 days for build and abtest
-fix inconsistency with change priorities inside DebuggingReport
-fix incorrect image for 'Same Content' in PriorityChoices

closes #171.
closes #172.
closes #176
closes #198.

some future reworking prbly needed

2021-05-15 18:46 UTC, reginawang99 requested changes
line 186-192 for `Game\index.tsx` is also wrong (mb that was my code)

2021-05-15 18:46 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/DebuggingResults.tsx
> +      daysMin: -10,
has to have minimum number days 1 so that we have days to allocate (it'll cause bugs/not allow continuing past the `TimeAllocation` phase)
```suggestion
      daysMin: 1,
```

2021-05-15 18:46 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/index.tsx
> +  const [targetWeights, setTargetWeights] = useState<number[]>([...DEFAULT_WEIGHTS]);
nit
```suggestion
  const [featureWeights, setFeatureWeights] = useState(DEFAULT_WEIGHTS);
  const [targetWeights, setTargetWeights] = useState<number[]>(DEFAULT_WEIGHTS);
```

2021-05-15 18:46 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/GameConstants.tsx
> +export const DEFAULT_TIME_ALLOCATION = {build: 7, abTest: 7};
this will cause issues if there are less than 14 days left

![image](https://user-images.githubusercontent.com/29292203/118374632-22391e80-b572-11eb-98e4-3881179e617b.png)

2021-05-15 19:06 UTC, tr89on commented on src/components/Activities/Activity3/Game/index.tsx
> +  const [targetWeights, setTargetWeights] = useState<number[]>([...DEFAULT_WEIGHTS]);
won't this cause a pass by reference issue?

2021-05-15 23:16 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/index.tsx
> +  const [targetWeights, setTargetWeights] = useState<number[]>([...DEFAULT_WEIGHTS]);
no? its a constant and won't be changed+line 54 does it, also can we put `DEFAULT_WEIGHTS` into `GameConstants`?

2021-05-16 00:08 UTC, tr89on commented on src/components/Activities/Activity3/Game/GameConstants.tsx
> +export const DEFAULT_TIME_ALLOCATION = {build: 7, abTest: 7};
ok I think i fixed this

2021-05-16 00:31 UTC, reginawang99 requested changes
just some smol things :') looks great overall tho!!

2021-05-16 00:31 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/DebuggingResults.tsx
> +    setDaysLeft(daysLeft + objectSum(timeAllocation));
i dont think you should get your `build` days back if you have already used them? i think we get back `abTest` time because we haven't gone through that phase yet

2021-05-16 00:31 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/index.tsx
> +      <TimeAllocation initialTimes={timeAllocation} isTutorial={true} />,
can we make it so that the `debug` in the tutorial still highlights `build` and stays in the same position? (eg 
![image](https://user-images.githubusercontent.com/29292203/118381722-d3f04380-b5a2-11eb-9476-5436265f41d1.png) highlights build + third highlights `abTest` properly)

2021-05-16 00:31 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/index.tsx
> +      <TimeAllocation initialTimes={timeAllocation} isTutorial={false} />,
ahhh we probs need some variation of this 
![image](https://user-images.githubusercontent.com/29292203/118381769-44976000-b5a3-11eb-9b32-ef4b5cb0c1cb.png)

i was thinking that if we have less than 14 days left, like 11 or something, it would auto allocate eg 6 and 5?

2021-05-16 00:38 UTC, tr89on commented on src/components/Activities/Activity3/Game/index.tsx
> +      <TimeAllocation initialTimes={timeAllocation} isTutorial={false} />,
wait do u remember how u triggered this

2021-05-16 00:43 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/index.tsx
> +      <TimeAllocation initialTimes={timeAllocation} isTutorial={false} />,
When u use up almost all the days and press remake product on abtest screen

2021-05-16 05:37 UTC, tr89on commented on src/components/Activities/Activity3/Game/DebuggingResults.tsx
> +    setDaysLeft(daysLeft + objectSum(timeAllocation));
Oh I thought it would be easier to keep their old time allocation because otherwise if they assigned 50 build days the 1st time then the debugging phase would have 0ish bugs but if they went back to improve recs, they would go through the debug phase with <6 build days and end up with a lot of bugs(?)

2021-05-16 05:39 UTC, tr89on commented on src/components/Activities/Activity3/Game/DebuggingResults.tsx
> +    setDaysLeft(daysLeft + objectSum(timeAllocation));
alternatively we could rename improve recs to improve recs + rebuild?

2021-05-16 05:41 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/DebuggingResults.tsx
> +    setDaysLeft(daysLeft + objectSum(timeAllocation));
ahhh yee i think renaming would be good, it is a lil misleading

2021-05-16 22:24 UTC, reginawang99 requested changes
just two lil nits then im ready to approve!! :)

2021-05-16 22:24 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/ABTestingReport/index.tsx
> +      <button className="playnet-button playnet-btn-blue" disabled={daysLeft < LOW_DAY_THRESHOLD} onClick={retry}>
nit: i think the `LOW_DAY_THRESHOLD` just happens to be 14 and should probably be sum of `DEFAULT_TIME_ALLOCATION` instead?
```suggestion
      <button className="playnet-button playnet-btn-blue" disabled={daysLeft < objectSum(DEFAULT_TIME_ALLOCATION)} onClick={retry}>
```

2021-05-16 22:24 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/TimeAllocation.tsx
> +            ? 'disable-blur highlight-border' : 'enable-blur')}`}>
wat lol can we make this less complex?
one idea is to throw highlighting stuffs into `tutorialStyles` or something

2021-05-17 02:50 UTC, reginawang99 requested changes
looks really good to me! one last smol thing, the bar no longer exists in the final report :(( lmk if you want my help figuring it out!

![image](https://user-images.githubusercontent.com/29292203/118426381-f3a96980-b67f-11eb-8d8e-e1fe5d36e7a1.png)

2021-05-17 03:34 UTC, reginawang99 approved these changes
looks good to me :)) ty for making all the requested changes!!

2021-05-17 03:34 UTC, merged