feat: Small Fixes + Replay Tutorial button
uclaacm/Playnet pull request #195
Opened 2021-05-11 07:48 UTC by darren2hang

- Remove the sound buttons from the last page of Activity 1 and Activity 2
- Move the intro slide into the activity 3 Game component
- change game to start at intro slide and not officially start until the slide after the first slide

closes #184 
closes #187 
closes #188

2021-05-11 19:52 UTC, reginawang99 requested changes
this also really isnt in scope, but would you mind removing controls on the last page of intro also?
![image](https://user-images.githubusercontent.com/29292203/117876052-bf851180-b257-11eb-97c1-4302353dc007.png)

2021-05-11 19:52 UTC, reginawang99 commented on .vs/ProjectSettings.json
> +{
can we remove this folder / add it to the `.gitignore`

2021-05-11 20:01 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/GameIntroSlides.tsx
> +      </div>
can we make this only in the right half? i think it looks a lil better that way! your choice tho after poking around!

2021-05-14 03:13 UTC, darren2hang commented
> this also really isnt in scope, but would you mind removing controls on the last page of intro also?
> ![image](https://user-images.githubusercontent.com/29292203/117876052-bf851180-b257-11eb-97c1-4302353dc007.png)

sure!

2021-05-14 03:26 UTC, darren2hang commented on .vs/ProjectSettings.json
> +{
yea, my bad. I pushed it by accident

2021-05-14 03:29 UTC, darren2hang commented on src/components/Activities/Activity3/Game/GameIntroSlides.tsx
> +      </div>
how would we do it if both the start button and the replay button are being displayed? Would both buttons be on the right? Or is it play game button on the right side and when both buttons are there we just have a button on each side?

2021-05-14 03:38 UTC, reginawang99 commented on src/components/Activities/Activity3/Game/GameIntroSlides.tsx
> +      </div>
maybe both on the right? 
![image](https://user-images.githubusercontent.com/29292203/118217899-3cb4b000-b42b-11eb-876d-1dcf559aebf4.png)

2021-05-14 03:46 UTC, reginawang99 approved these changes
LGTM!! 🎉

2021-05-14 03:47 UTC, merged