feat: datacenter animation
uclaacm/Playnet pull request #22
Opened 2021-02-18 21:23 UTC by reginawang99

- data center animations for intro slides 8-12 with AE + Lottie
- added in a LottieController for the animations

2021-02-18 23:12 UTC, BryanPan342 requested changes
its a nice first pass! but i have a couple of suggestions to reduce the file footprint!

Also, it would be nice if the assets under `lottie_animation_data/` were more descriptive

nit means its up to u if u want to change it.

2021-02-18 23:12 UTC, BryanPan342 commented on src/components/Home/Intro11.tsx
> +    </div>
this code seems a bit repetitive.. can we do something along the lines of the following in `Home.tsx` or `Home/index.tsx`

```
import Intro10Data from 'LottieAnimations/Intro10Animation';
...

import LottieControl from '../shared/LottieController';

const slides = [
  'There are data centers all over the world.',
  ...
];

function Home(): JSX.Element {
  return (
    <div>
      <Base section={HeaderSections.INTRO}>
        <Carousel
              ...>
           {slides.map((text, i) => {
               <div>
                  <h2 id={'body-text'}> {text} </h2>
                  <LottieControl animationData={eval(`Intro${i+7}Data`)} />
               </div>
           })}
        </Carousel>
       ...
```

Basically, since each slide is almost always gonna look the same, let's dynamically create them so that if we need to change one slide they will all match!

2021-02-18 23:12 UTC, BryanPan342 commented on src/components/shared/LottieController.tsx
> +  </div>;
nit

```suggestion
  return (
    <div>
      <Lottie options={defaultOptions} />
    </div>
  );
```

2021-02-18 23:12 UTC, BryanPan342 commented on src/components/Home/Intro11.tsx
> +    </div>
actually 

i dont see why we can't just make components for both the lottie animations and the images themselves

2021-02-18 23:12 UTC, BryanPan342 commented on src/components/Home/Intro10.tsx
> +import Intro10Data from '../LottieAnimations/Intro10Animation';
nvm i figured it out

2021-02-18 23:18 UTC, reginawang99 commented on src/components/Home/Intro11.tsx
> +    </div>
yeaaa definitely, i totally agree. i think we were thinking of making the carousel have more power and having carousel item #19 then we can have the text as a prop in each item
lmk what you think!

2021-02-18 23:20 UTC, reginawang99 commented
oh yeaa definitely i totally agree about the descriptive names, id have to change the hardcode in all the json exports (which was predetermined by lottie) which might make it a bit confusing if we change the animation. maybe i can do that when everything else looks good to go

2021-02-19 00:09 UTC, BryanPan342 commented on src/components/Home/Intro11.tsx
> +    </div>
okay i see.. then lets do it in #19 to simplify

2021-02-19 06:02 UTC, BryanPan342 approved these changes
okay im good with this if we make tickets for the renaming!

2021-02-19 06:02 UTC, merged