Carouselitem
uclaacm/Playnet pull request #23
Opened 2021-02-22 17:50 UTC by reginawang99

2021-02-22 18:45 UTC, arjunr00 reviewed
Looks good! Just a couple minor things

2021-02-22 18:45 UTC, arjunr00 commented on src/components/CarouselItem.tsx
> +  children: JSX.Element;
nit: Since this is a single element and not an array, I think a name like `child` would be a tad bit clearer

2021-02-22 18:45 UTC, arjunr00 commented on src/components/Carousel.tsx
> +            </div>
nit: Since `CarouselItem` is a sort of container for each "slide", I think it would be appropriate to have the `CarouselItem` contain the top and bottom text inside it. Something like this:
```suggestion
            <CarouselItem goNextSlide={function () { return goNextSlide(slideIdx); }}
              goPrevSlide={function () { return goPrevSlide(slideIdx); }}
              timeout={props.children[slideIdx].animationTime}>
              <div>
                {props.children[slideIdx].topText && <h2 id={'body-text'}> {props.children[slideIdx].topText} </h2>}
                {props.children[slideIdx].child}
                {props.children[slideIdx].bottomText && <h2 id={'body-text'}> {props.children[slideIdx].bottomText} </h2>}
              </div>
            </CarouselItem>
```
(note: I think this rearrangement shouldn't break alignment and stuff, but maybe double check on your end to be sure)

2021-02-22 21:27 UTC, BryanPan342 requested changes
I like where this PR is going but I'm a little confused on the showNext stuff some of functionality

I feel like we should add additional props when we need them immediately, nice-to-haves are nice but can always be added later imo

2021-02-22 21:27 UTC, BryanPan342 commented on src/components/CarouselItem.tsx
> +  showPrev?: boolean;
why do we need these?

2021-02-22 21:27 UTC, BryanPan342 commented on src/components/Carousel.tsx
> +                (props.children[slideIdx].showPrev !== undefined && props.children[slideIdx].showPrev)))
this logic is pretty complicated imo, and I'm not entirely sold on each child having the ability to not show the previous button.. i cant really think of a situation where that holds unless the slide is an activity.

If it is an activity we should just have a type guard to check instead of having a prop determine it. If not I think all slides should have the same UX

2021-02-22 21:27 UTC, BryanPan342 commented on src/components/CarouselItem.tsx
> +  }
i think the Carousel should manage its own state! Meaning the timeout logic for the animation to happen in in the Carousel component itself, not the child

2021-02-22 21:27 UTC, BryanPan342 commented on src/components/Carousel.tsx
> +                || (props.children[slideIdx].showNext !== undefined && props.children[slideIdx].showNext))
same comment as with the prev button

2021-02-22 21:27 UTC, BryanPan342 commented on src/components/Carousel.tsx
> +  }
why do we need this function?

i feel like we can have a useEffect hook to check if we are on our last child component and if so return to home?

2021-02-22 21:27 UTC, BryanPan342 commented on src/components/Carousel.tsx
> +            </div>
+1 this

i also have been seeing the `props.children[slideIdx]` a lot.. can we make this a state variable?

```ts
const [child, setChild] = useState(props.children[slideIdx]);

useEffect(() => {
  setChild(props.children[slideIdx]);
}, [slideIdx]);

```

2021-02-22 21:27 UTC, BryanPan342 commented on src/components/Home/index.tsx
> +          }}
nit: change this to an array (not sure why I prefer this but just something to think about)

i think the following will allow us to do component generation through function if we want to later on

```ts
function Home(): JSX.Element {
  const content = [
    {
       child: <LottieControl animationData={Intro8Data} />,
       topText: 'This is a real-life data center at Google!',
    },
   ...
  ];
  return (
    <Base section={HeaderSections.INTRO}>
      <Carousel>
         {content}
      ...
  );
}

```

2021-02-24 08:15 UTC, reginawang99 commented
i resolved a lot of things because we are using useContext hook instead of props chaining!

2021-02-24 08:47 UTC, reginawang99 commented on src/components/Carousel.tsx
> +  }
no particular reason, just to make the code easier to read! but yee i agree that this shouldn't even be necessary in the first place

2021-02-24 08:49 UTC, reginawang99 commented on src/components/Carousel.tsx
> +                (props.children[slideIdx].showPrev !== undefined && props.children[slideIdx].showPrev)))
i think we talked about this on fb haha

2021-02-24 08:50 UTC, reginawang99 commented on src/components/CarouselItem.tsx
> +  showPrev?: boolean;
took offline! *

2021-02-24 08:50 UTC, reginawang99 commented on src/components/Carousel.tsx
> +  }
yup, no need since we using useContext

2021-02-24 08:58 UTC, reginawang99 commented on src/components/Carousel.tsx
> +            </div>
hmm since its a one to one render (for every change in slideIdx, child also rerenders once) , i don't quite see why child should be a state variable? 

it could just be a temporary value, like `child = props.children[slideIdx]`?

2021-02-24 09:34 UTC, reginawang99 commented on src/components/CarouselItem.tsx
> +  }
ok! ill throw the animation time stuffs into another diff tho

2021-02-24 10:12 UTC, reginawang99 commented on src/components/Home/index.tsx
> +          }}
i agree the array is cleaner looking

2021-02-24 10:15 UTC, reginawang99 commented on src/components/Home/index.tsx
> +          }}
i dont mind, sgtm!

2021-02-24 18:18 UTC, BryanPan342 requested changes
Wowzas its looking really good 😊

I got a couple of nits and suggestions that I want to bring up before I'm ready to merge this!

2021-02-24 18:18 UTC, BryanPan342 commented on src/components/Carousel.tsx
> +                  (child.showPrev === true))
thanks! this is a lot more readable than the last one!

nit:
```suggestion
              visibility: child?.showPrev === false || slideIdx === 0 ? 'hidden' : 'visible'
```

the `?` operator is syntactic sugar to see if the child is defined before resolving the property

2021-02-24 18:18 UTC, BryanPan342 commented on src/components/Carousel.tsx
> +                  : 'hidden',
same as above

nit:
```suggestion
              visibility: child?.showNext === false || slideIdx === props.children.length - 1
                  ? 'hidden'
                  : 'visible,
```

2021-02-24 18:18 UTC, BryanPan342 commented on src/components/Carousel.tsx
> +export const ChangeSlideContext = React.createContext({next: () => { }, prev: () => { }});
remove the eslinter ignore line for the following

```suggestion
export const CarouselContext = React.createContext({
  next: () => undefined,
  prev: () => undefined,
});
```

2021-02-24 18:18 UTC, BryanPan342 commented on src/components/Carousel.tsx
> +  }
hm something tells me that this should be in the `slideIdx`  useEffect hook with `child` being a state variable...

I also think the goPrev and goNext function protect our slideIdx from being crazy values, so i think the conditional statement might be overkill

2021-02-24 18:18 UTC, BryanPan342 commented on src/components/Carousel.tsx
> +    <ChangeSlideContext.Provider value={{next: goNext, prev: goPrev}}>
nit:
```suggestion
    <CarouselContext.Provider value={{next: goNext, prev: goPrev}}>
```

2021-02-24 18:18 UTC, BryanPan342 commented on src/components/Carousel.tsx
> +          </div>
seems to me that the id carousel-content should be sufficient to encompass all of this! essentially i want to remove unnecessary divs if we dont need them!

I have two ideas on how to take this:

```suggestion
          { child &&
            <div id={'carousel-content'}>
              {child.topText && <h2 id={'body-text'}> {child.topText} </h2>}
              {child.child}
              {child.bottomText && <h2 id={'body-text'}> {child.bottomText} </h2>}
            </div>
          }
```

OR

```suggestion
          <div id={'carousel-content'}>
            { child &&
              <>
                {child.topText && <h2 id={'body-text'}> {child.topText} </h2>}
                {child.child}
                {child.bottomText && <h2 id={'body-text'}> {child.bottomText} </h2>}
              </>
            }
          </div>
```

@arjunr00 need a second opinion on this

2021-02-24 19:40 UTC, arjunr00 commented on src/components/Carousel.tsx
> +          </div>
I agree, plus I think the second one is better just in terms of consistency

2021-02-24 19:40 UTC, reginawang99 commented on src/components/Carousel.tsx
> +                  (child.showPrev === true))
genius :0

2021-02-24 22:11 UTC, BryanPan342 requested changes
One more suggestion 😅 after that I'm ready to 🚀 this

2021-02-24 22:11 UTC, BryanPan342 commented on src/components/Carousel.tsx
> +    setChild(props.children[slideIdx]);
Lets add this to the above useEffect hook!

2021-02-24 22:11 UTC, BryanPan342 commented on public/index.html
> +        <base href="/" />
Is this needed?

2021-02-24 22:12 UTC, reginawang99 commented on public/index.html
> +        <base href="/" />
no haha

2021-02-24 22:47 UTC, BryanPan342 approved these changes
LGTM 🥳

2021-02-24 22:47 UTC, merged