feat: create 2nd game for activity 1
uclaacm/Playnet pull request #37
Opened 2021-02-26 21:47 UTC by tr89on

<ul>
 <li> created base implementation for game2 </li>
 <li> implemented use-sound hook for SFX </li>
 <li> updates webpack.dev.js to support .mp3 files </li>
</ul>

Closes #14 

Possible future issues(?)
<ul>
 <li> Sound toggle to enable/disable SFX </li>
</ul>

2021-03-07 09:57 UTC, reginawang99 requested changes
wow looks super great! much reusable+sleek and thanks for setting up the sound stuff! just some small modifications to get playGame button and the sounds working on prod

2021-03-07 09:57 UTC, reginawang99 commented on src/components/Activities/Activity1/Game2/components/SlideBox.tsx
> +  const INCORRECT_RED = '#FF0000';
maybe we can put these in playnetConstants file as something like `public enum PlaynetColors` or something for consistency :)

2021-03-07 09:57 UTC, reginawang99 commented on src/components/Activities/Activity1/Game2/components/SlideBox.tsx
> +    }
```suggestion
    let newBorder = (border === INCORRECT_RED) ? INCORRECT_RED : color;
```

2021-03-07 09:57 UTC, reginawang99 commented on src/components/Activities/Activity1/Game2/index.tsx
> +function AmbiguousGame(): JSX.Element {
nit: more descriptive component name, i read it as that the game was ambiguous 🤦 
```suggestion
function AmbiguousPhrasingGame(): JSX.Element {
```

2021-03-07 09:57 UTC, reginawang99 commented on src/components/Activities/Activity1/Game2/index.tsx
> +
nit: remove empty space!
```suggestion
```

2021-03-07 09:57 UTC, reginawang99 commented on src/components/Home.tsx
> +import React from 'react';
oh nu i dont think this should be here, you can remove this file!

2021-03-07 09:57 UTC, reginawang99 commented on webpack.dev.js
> +      {
add these changes to the webpack.prod.js and it should work on netlify as well! 

this is because on dev, the webpack will take webpack.common.js and webpack.dev.js, while in prod, webpack will take webpack.common.js and webpack.prod.js

2021-03-07 09:57 UTC, reginawang99 commented on src/components/Activities/Activity1/index.tsx
> +  const context = useContext(CarouselContext);
so actually, you have to make sure to `useContext` under the tree of where the `CarouselContext` is set. In this case, since `Activity2` is not _in_ a carousel, this won't give you what you want

2021-03-07 09:57 UTC, reginawang99 commented on src/components/Activities/Activity1/index.tsx
something like this is probably what you want so that when `AmbiguousPhrasingGameIntro` is rendered, it is rendered within `Carousel`, so the `CarouselContext` will be passed properly!
```suggestion
  const AmbiguousPhrasingGameIntro = () => {
    const context = useContext(CarouselContext);
    return (
      <div id="game2-intro">
          <span>But even if we know what the alien is saying...can you figure out what they mean?</span>
          <br/>
          <span>Warning: One sentence can mean two things, so the answer might not be what you expect!</span>
          <br/>
          <button id="game2-intro-button" onClick={context.next}>
            Play Game
          </button>
        </div>
    );
  };
```

2021-03-07 09:57 UTC, reginawang99 commented on src/components/Activities/Activity1/index.tsx
> +        </div>,
something like this is probably what you want so that when `AmbiguousPhrasingGameIntro` is rendered, it is rendered within `Carousel`, so the `CarouselContext` will be passed properly!
```suggestion
     child: <MiniGame2Intro/>,
      showNext: false,
```

2021-03-07 09:57 UTC, reginawang99 commented on webpack.dev.js
> +        test: /\.(mp3)$/i,
actually, could you add this to line 23? so the linecould look something like `test: /\.(png|svg|jpe?g|gif)$/i`

this is so that the file loaders stick together and the final folder will look like `assets/correct.mp3`
(something like [this!](https://deploy-preview-37--play-net.netlify.app/assets/pair1a.svg))

2021-03-07 22:25 UTC, tr89on commented on src/components/Activities/Activity1/index.tsx
> +  const context = useContext(CarouselContext);
Oh cool that makes sense!

2021-03-07 22:37 UTC, tr89on commented on src/components/Activities/Activity1/Game2/components/SlideBox.tsx
> +    }
Cool, I didn't think about using a ternary here!

2021-03-07 22:44 UTC, tr89on commented on webpack.dev.js
> +      {
Ooo I see good to know!

2021-03-07 22:48 UTC, tr89on commented on webpack.dev.js
> +        test: /\.(mp3)$/i,
Yee ty for all the suggestions 🤙

2021-03-12 20:49 UTC, BryanPan342 requested changes
almost ready to approve this! have a couple of suggestions but happy to hear what you think as well :)

2021-03-12 20:49 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game2/components/GameSlide.tsx
> +  imgOption1 ?: string;
```suggestion
  correctImg?: number;
  advanceGame?: () => void;
  textDefault?: string;
  textIncorrect?: string;
  imgs?: string[],
```

and then you can destructure images later

2021-03-12 20:49 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game2/components/GameSlide.tsx
> +  const img1 = props.imgOption1;
```suggestion
const [img0, img1] = props.imgs;
```

2021-03-12 20:49 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game2/components/GameSlide.tsx
> +  imgOption1 ?: string;
you could also always have the first image in `imgs` ALWAYS be the right image..

so `imgs = [correct, incorrect]`

2021-03-12 20:49 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game2/components/GameSlide.tsx
> +        <img src={AlienSvg} />
lets add an alt tag here!

2021-03-12 20:49 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game2/index.tsx
> +    setSlideIdx(nextSlide);
so i think this can be simplied to something like the following
```suggestion
    if (slideIdx === slides.length-1) {
      context.next();
    }
    setSlideIdx(slideIdx+1);
```

The reason why we can get rid of nextSlide is because

1. we check if the slideIdx is equal to slides.length-1.. aka are we on the last slide 
2. Since slideIdx is not tied down to another mutator and only this `setSlideIdx` will affect it, we can always assume that slideIdx will increase by only 1
3. so because of statement 1, we know that the Carousel will move onto the next component when we reach the end, and we know that slideIdx can only increase

We can also remove the check for slideIdx to be zero because if the slideIdx is zero and it is at the end of the slides, we should move onto the next Carousel component

2021-03-12 20:49 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game2/index.tsx
> +        advanceGame={advanceGame}
very clean :) i like this

2021-03-13 03:35 UTC, tr89on commented on src/components/Activities/Activity1/Game2/index.tsx
> +    setSlideIdx(nextSlide);
Oh yea that makes sense!

2021-03-13 03:37 UTC, tr89on commented on src/components/Activities/Activity1/Game2/components/GameSlide.tsx
> +  imgOption1 ?: string;
Ooo cool idea

2021-03-13 03:38 UTC, reginawang99 commented on src/components/Activities/Activity1/Game2/components/GameSlide.tsx
> +  imgOption1 ?: string;
@tr89on can we add a comment that the first image is `correct` and the second is `incorrect`? this is for easier reuse by others so they don't necessarily have to read all the code to figure out how to use your component!

2021-03-13 03:42 UTC, reginawang99 approved these changes
looks great to me! 🎉🥳 

all bryans now :)

2021-03-13 03:47 UTC, reginawang99 commented on src/components/Activities/Activity1/Game2/components/GameSlide.tsx
> +  imgOption1 ?: string;
actually nvm just realized you have a `correctImg` prop!

2021-03-13 05:14 UTC, BryanPan342 requested changes
thanks for the changes! just a couple of nits before I'm ready to full send this :)

2021-03-13 05:14 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game2/components/SlideBox.tsx
> +    setBorder(newBorder);
```suggestion
    if (border === PlaynetColors.INCORRECT_RED) return;
    setBorder(color);
```
try to avoid state changes!

2021-03-13 05:14 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game2/components/SlideBox.tsx
> +      onMouseLeave={() => handleHover(BLACK)}
why not set the `css:hover` selector to deal with the border?

2021-03-13 05:14 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game2/components/GameSlide.tsx
> +}
why are these optional?

i see that we always use them

2021-03-13 05:14 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game2/components/GameSlide.tsx
> +  };
```suggestion
  const handleClick = (pos : number) => {
    if (pos !== props.correctImg) {
      playIncorrect();
      setIncorrect(true);
      return;
    } 
    playCorrect();
    advanceGame();
  };
```

2021-03-13 05:14 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game2/components/GameSlide.tsx
> +  };
i think because react will have to update again, you don't need to setIncorrect to false.. might be wrong tho..

if so you can add a useEffect to make sure its false.

2021-03-14 22:58 UTC, tr89on commented on src/components/Activities/Activity1/Game2/components/GameSlide.tsx
> +  };
Oh ok isn't there something bad about making state changes inside an if statement tho?

2021-03-16 21:18 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game2/components/GameSlide.tsx
> +  };
Hmm ur right.. okay I'm cool with this then

2021-03-16 21:18 UTC, BryanPan342 approved these changes
LGTM 🥳🥳 congrats on the PR!! Really nice work

2021-03-16 21:18 UTC, merged

2021-03-16 21:19 UTC, darren2hang reviewed
When the incorrect choice is selected on the first option, the text goes outside of the textbubble. The cause of this is problem from the centered class in the TextBubble.scss file. I think it has something to do with the position: absolute and the left 50% used in order to center to text in the text bubbles. I tried playing around with the css but I couldn't figure out how to make the text full width while still keeping all the text centered in the middle of the textbubble (my css isn't the best).
Maybe Regina or Bryan know how to fix this.
![alienTextBubbleOverflow](https://user-images.githubusercontent.com/56695604/111381113-7ef78600-8662-11eb-92b9-b11b3be4c5d9.jpg)
Everything else looks good to me! I think you did a very good job!

2021-03-16 21:19 UTC, darren2hang commented on src/components/Activities/Activity1/index.tsx
> +              When you&apos;re older, you&apos;ll get the chance to learn how to code you that you can
There's a typo. It should be "learn how to code so" not "learn how to code you"