feat: made first 3 screens of activity 1
uclaacm/Playnet pull request #38
Opened 2021-02-26 22:32 UTC by darren2hang

- Made TextBubble component that displays cartton speech bubbles
- Made Convo component that can display multiple text bubbles in a row
- fixed EOL to LF
Closes: #11

2021-02-26 22:49 UTC, reginawang99 commented on src/assets/lost-in-translation.svg
> -<svg width="350" height="270" viewBox="0 0 350 270" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
oop no yarn lint here pls

2021-02-26 22:51 UTC, darren2hang commented on src/assets/lost-in-translation.svg
> -<svg width="350" height="270" viewBox="0 0 350 270" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
ok thanks! I removed it. I think I fixed everything

2021-02-26 23:20 UTC, tr89on commented
from a visual standpoint there's a lot of white space around each slide on my monitor, so not sure if scaling/centering it would be better (subjective)---this might have more to do with how the carousel display works though

![Screen Shot 2021-02-26 at 3 02 26 PM](https://user-images.githubusercontent.com/22901219/109364428-a4ebf080-7843-11eb-9966-79b628cd6acc.png)

other than that the slides look good and the animation is clean 😎

2021-02-26 23:56 UTC, tr89on commented on src/components/Activities/Activity1/TextBubble.tsx
> +      {(props.textBubbleStyle === TextBubbleStyles.SMALL_RIGHT) ? <img src={SmallRightTextBubbleSvg} />: <span></span>}
Instead of returning a bunch of empty <span> it might be better to just return '' (empty string) for the unused textbubble styles

2021-02-27 00:15 UTC, tr89on commented on src/components/Activities/Activity1/Convo.tsx
> +      {props.phrases.map(displaySpeechBubbles)}
this could just be a single function to display current textBubble instead of map--right now it's effectively only displaying 1 bubble at a time (?) since the other list items return empty divs (similar to the empty `<span>`)

2021-02-27 06:32 UTC, reginawang99 requested changes
Looks great! thanks for doing this! :) just some changes to help the code be more easy to read+reuse

2021-02-27 06:32 UTC, reginawang99 commented on src/components/Activities/Activity1/TextBubble.tsx
> +      {(props.textBubbleStyle === TextBubbleStyles.SMALL_RIGHT) ? <img src={SmallRightTextBubbleSvg} />: <span></span>}
try to minimize divs/brs/spans in final result unless you have a reason for them
```suggestion
  let image;
  image = (props.textBubbleStyle === TextBubbleStyles.EXTRA_LARGE) ? ExtraLargeTextBubbleSvg : image;
  image = (props.textBubbleStyle === TextBubbleStyles.LARGE) ? LargeTextBubbleSvg : image;
  image = (props.textBubbleStyle === TextBubbleStyles.MEDIUM) ? MediumTextBubbleSvg : image;
  image = (props.textBubbleStyle === TextBubbleStyles.SMALL_LEFT) ? SmallLeftTextBubbleSvg : image;
  image = (props.textBubbleStyle === TextBubbleStyles.SMALL_RIGHT) ? SmallRightTextBubbleSvg : image;

  return (
    <div className='text-bubble'>
      {(!image) ? <></> : <img src={image} />}
```

2021-02-27 06:32 UTC, reginawang99 commented on src/components/Activities/Activity1/TextBubble.tsx
> +      {(props.textBubbleStyle === TextBubbleStyles.SMALL_RIGHT) ? <img src={SmallRightTextBubbleSvg} />: <span></span>}
also, we are a bit far along so i don't think we need to go back and change it, but take a look at [this commit,](https://github.com/uclaacm/Playnet/commit/346638eb72dc4fe1de5e0e34093fec9f7bc49051) it uses id to specify background image rather than doing all these ternary operations

2021-02-27 06:32 UTC, reginawang99 commented on src/components/Activities/Activity1/index.tsx
> +        <div id='slide-3'>
nit (not important, feel free to dismiss): make this its own functional component (possibly in same file or not) since its a bit long and clogs up the content area

2021-02-27 09:12 UTC, BryanPan342 commented on src/components/Activities/Activity1/TextBubble.tsx
> +      {(props.textBubbleStyle === TextBubbleStyles.SMALL_RIGHT) ? <img src={SmallRightTextBubbleSvg} />: <span></span>}
I would recommend the div method because it becomes a lot more readable!

2021-02-27 09:15 UTC, BryanPan342 commented on src/components/Activities/Activity1/Convo.tsx
> +      return <div className='fade' style={{animationDuration: 2/3*props.delayTime/1000+'s'}}>
@reginawang99  we can switch these all to anime.js! it makes doing all of these animations 10x easier :)

I'll make a PR this weekend to showcase its p0wer

2021-02-27 09:24 UTC, BryanPan342 requested changes
I havent done a thorough review yet, because you have two reviews already, BUT congrats on your first PR for `Playnet`

I'll add more of my thoughts as your resolve these other reviews 😊 Keep at it!

2021-02-27 09:24 UTC, BryanPan342 commented on src/assets/sending-videos.svg
> +
remove this unnecessary white space!

2021-02-27 09:24 UTC, BryanPan342 commented on src/components/Activities/Activity1/Convo.tsx
> +      if (i === 0 && props.offset !== undefined && props.phrases[i] === ''){
in general, nested conditional statements leads to less readable code

I guess, one of my questions is.. when would `props.phrases[i]` ever not equal `text` (which is just props.phrases[i]...)

2021-02-27 23:50 UTC, reginawang99 commented on src/components/Activities/Activity1/TextBubble.tsx
> +      {(props.textBubbleStyle === TextBubbleStyles.SMALL_RIGHT) ? <img src={SmallRightTextBubbleSvg} />: <span></span>}
@BryanPan342 div method? as in the original? or

2021-02-28 01:10 UTC, BryanPan342 commented on src/components/Activities/Activity1/TextBubble.tsx
> +      {(props.textBubbleStyle === TextBubbleStyles.SMALL_RIGHT) ? <img src={SmallRightTextBubbleSvg} />: <span></span>}
like using a div element and having the background image be associated with an id!

2021-02-28 02:47 UTC, reginawang99 commented on src/components/Activities/Activity1/TextBubble.tsx
> +      {(props.textBubbleStyle === TextBubbleStyles.SMALL_RIGHT) ? <img src={SmallRightTextBubbleSvg} />: <span></span>}
ya sounds good to me! in fact, this would remove the funny delayed rendering thing you had @darren2hang if you specify width and height for each image! hmu if you have more questions :)

2021-02-28 08:47 UTC, darren2hang commented on src/components/Activities/Activity1/TextBubble.tsx
> +      {(props.textBubbleStyle === TextBubbleStyles.SMALL_RIGHT) ? <img src={SmallRightTextBubbleSvg} />: <span></span>}
That's a really good idea! I didn't think of that.

2021-02-28 09:06 UTC, darren2hang commented on src/assets/sending-videos.svg
> +
Ok!

2021-02-28 09:08 UTC, darren2hang commented on src/components/Activities/Activity1/Convo.tsx
> +      {props.phrases.map(displaySpeechBubbles)}
Yep, you're right!

2021-02-28 09:16 UTC, darren2hang commented on src/components/Activities/Activity1/Convo.tsx
> +
like a different delay/pause time for each word? That would actually be pretty useful for it there were longer words in the convo

2021-02-28 10:17 UTC, darren2hang commented on src/components/Activities/Activity1/TextBubble.tsx
> +      {(props.textBubbleStyle === TextBubbleStyles.SMALL_RIGHT) ? <img src={SmallRightTextBubbleSvg} />: <span></span>}
ok, i changed it to use background id.

2021-02-28 10:32 UTC, darren2hang commented on src/components/Activities/Activity1/Convo.tsx
> +      if (i === 0 && props.offset !== undefined && props.phrases[i] === ''){
This was a workaround because I couldn't think of a way to make a offset time before starting the display of phrases. So i just made the first phrase empty to add an offset time. I just removed this though.

2021-02-28 10:35 UTC, darren2hang commented on src/components/Activities/Activity1/Convo.tsx
> +    if (i === 0 && props.offset !== undefined && props.phrases[i] === '')
i removed this and reimplemented how the offset works.

2021-02-28 20:18 UTC, reginawang99 commented on src/components/Activities/Activity1/Convo.tsx
> +
yup! maybe it can be defaulted to timeBtwnPhrases if not specified

2021-02-28 20:22 UTC, reginawang99 commented on src/components/Activities/Activity1/TextBubble.tsx
> +  contentSvg?: string;   //if broken change back to any
@BryanPan342 what do u think, should we do `any` for the images , or have an enum that specifies image, or ? i think string is p misleading

2021-02-28 21:44 UTC, BryanPan342 commented on src/components/Activities/Activity1/TextBubble.tsx
> +  contentSvg?: string;   //if broken change back to any
im gonna need to review the entire thing before I make a judgement, but just by the looks of it, maybe we should name it something like `svgPath` or smth like that?

2021-03-03 07:07 UTC, darren2hang commented on src/components/Activities/Activity1/Convo.tsx
> +
I changed it to an array of Phrases I didn't know you could accept suggestions through github so I didn't accept the commit suggestion. Sorry lol.

2021-03-03 07:08 UTC, darren2hang commented on src/components/Activities/Activity1/Convo.tsx
> +  phrases: string[],
i just made this change!

2021-03-03 07:08 UTC, darren2hang commented on src/components/Activities/Activity1/Convo.tsx
> +        {(props.phrases[i].indexOf('.svg') === -1) ?
I just made this change!

2021-03-03 07:09 UTC, darren2hang commented on src/components/Activities/Activity1/Convo.tsx
> +  phrases: string[],
i just made this change!

2021-03-03 07:16 UTC, darren2hang commented
> from a visual standpoint there's a lot of white space around each slide on my monitor, so not sure if scaling/centering it would be better (subjective)---this might have more to do with how the carousel display works though
> 
> ![Screen Shot 2021-02-26 at 3 02 26 PM](https://user-images.githubusercontent.com/22901219/109364428-a4ebf080-7843-11eb-9966-79b628cd6acc.png)
> 
> other than that the slides look good and the animation is clean 😎

I think regina said she would address this in the carousel content.

2021-03-03 16:59 UTC, reginawang99 requested changes
just a super tiny change 😅 and then im good to go!

2021-03-03 16:59 UTC, reginawang99 commented on src/components/Activities/Activity1/Convo.tsx
> +
nit: remove extra space
```suggestion
```

2021-03-03 16:59 UTC, reginawang99 commented on src/components/Activities/Activity1/Convo.tsx
> +  waitTimeBeforeStart?: number,
ah actually looking now, it doesn't seem like this is necessary since it's simply text = '' and bubble style is none😅, i think this might add a bit of unnecessary complexity (like state variable and such); my b for not cathcing it sooner

2021-03-03 16:59 UTC, reginawang99 commented on src/components/Activities/Activity1/Convo.tsx
> +    if (props.waitTimeBeforeStart !== undefined && !offsetYet) {
```suggestion
    // setup empty text bubble 
    if (props.waitTimeBeforeStart !== undefined && !offsetYet) {
```

2021-03-03 16:59 UTC, reginawang99 commented on src/components/Activities/Activity1/Convo.tsx
> +
```suggestion

      // setup text bubble with contents
```

2021-03-03 17:16 UTC, reginawang99 requested changes

2021-03-03 17:16 UTC, reginawang99 commented on src/components/Activities/Activity1/Convo.tsx
> +  waitTimeBeforeStart?: number,
actually looking at how it needs a state variable and such, i think it might be unnecessary complexity, my b for not catching sooner 😅 can we make so empty is just TextBubbleStyle.NONE and text = ''? thanks!
```suggestion
```

2021-03-03 17:16 UTC, reginawang99 commented on src/components/Activities/Activity1/Convo.tsx
> +  const [offsetYet, setOffSetYet] = useState(false);
```suggestion
```

2021-03-03 17:16 UTC, reginawang99 commented on src/components/Activities/Activity1/Convo.tsx
> +
as per above!
```suggestion
```

2021-03-03 17:16 UTC, reginawang99 commented on src/components/Activities/Activity1/Convo.tsx
> +    } else if (i < props.phrases.length - 1) {
as per above!
```suggestion
  useEffect(() => {
    if (i < props.phrases.length - 1) {
```

2021-03-03 17:16 UTC, reginawang99 commented on src/components/Activities/Activity1/index.tsx
> +    {
as per above!
```suggestion
    {
      text: '',
      isText: true,
      timeOnScreen: timeBtwnWords / 2,
      textBubbleStyle: TextBubbleStyles.NONE,
    },
```

2021-03-03 17:16 UTC, reginawang99 commented on src/components/Activities/Activity1/index.tsx
> +            <Convo phrases={computerGuesses} timeBtwnPhrases={timeBtwnWords} waitTimeBeforeStart={timeBtwnWords / 2}
as per above!
```suggestion
            <Convo phrases={computerGuesses} timeBtwnPhrases={timeBtwnWords}
```

2021-03-03 17:17 UTC, reginawang99 commented
ahh as per the carousel stuffs, im not actually sure whats better, maybe we can also discuss with the designers later!

2021-03-04 03:29 UTC, reginawang99 approved these changes
yay nice nice nice nice LGTM!! 🎉

2021-03-04 03:47 UTC, BryanPan342 approved these changes
LGTM congrats on ur first PR :)

2021-03-04 03:48 UTC, merged