YouTube Landing Page
uclaacm/Playnet pull request #39
Opened 2021-03-02 05:23 UTC by Phreakester

This will create the intro and last slide for the website. The user chooses a video, which is then passed to the Home component to be used by the rest of the content in the carousel. After the video is chosen, the carousel is shown. After the carousel is finished, it switches to the final slide of the intro.

2021-03-03 02:12 UTC, arjunr00 submitted a review, later dismissed
looks good to me! just a few tiny nitpicks :)

2021-03-03 02:12 UTC, arjunr00 commented on src/components/Home.tsx
> +  const [ showCarousel, toggleCarousel ] = useState(false);
nit: just for clarity's sake, I think it would be better to keep the convention that the second element of the array, which is the setter, is of the form set<Value> where <Value> is the name of the state variable. Like this:
```suggestion
  const [ chosenVideoPath, setChosenVideoPath ] = useState(null);
  const [ showCarousel, setShowCarousel ] = useState(false);
```
I think this also helps distinguish regular functions from state-modifying ones!

2021-03-03 02:12 UTC, arjunr00 commented on src/components/Youtube.tsx
> +                <p id={"intro-subtitle"}>Now find out whats going on behind the scenes!</p>
nit:
```suggestion
                <p id={"intro-subtitle"}>Now find out what's going on behind the scenes!</p>
```

2021-03-03 02:12 UTC, arjunr00 commented on src/components/Youtube.tsx
> +                <h1 id={"intro-title"}>Want to learn how youtube works?</h1>
nit:
```suggestion
                <h1 id={"intro-title"}>Want to learn how YouTube works?</h1>
```

2021-03-03 02:50 UTC, reginawang99 requested changes
omg the hover is hella cute idk why :')

also how should we get to the activities? i think it would be more intuitive if there were a next button or someway to get to activities without the top bar? (maybe a next button?? :0)

2021-03-03 02:50 UTC, reginawang99 commented on src/components/Carousel.tsx
>    const [ slideIdx, setSlideIdx ] = useState(0);
not important, but you autoformat this file? thanks!

2021-03-03 02:50 UTC, reginawang99 commented on src/components/Home.tsx
> +        { showCarousel ? <Carousel
nit, not important, feel free to dismiss: can we make the carousel on a new line so that its easier to read?
```suggestion
        { showCarousel ? 
           <Carousel
```

2021-03-03 02:50 UTC, reginawang99 commented on src/components/Home.tsx
> +          <div><h1>First</h1></div>
it'd probably be a good idea to pull master and merge the files since it can't be commited otherwise!

2021-03-03 02:50 UTC, reginawang99 commented on src/components/Youtube.tsx
> +                        <img  id={"final-thumbnail"} src={props.chosenVideo} />
can we autoplay and mute the video? that would be cool :) https://www.w3schools.com/html/html_youtube.asp

2021-03-03 02:50 UTC, reginawang99 commented on src/components/Youtube.tsx
> +                <h1 id={"intro-title"}>Yay! Your video is ready to watch!</h1>
```suggestion
                <h1 id={"intro-title"}>Yay! Your video is ready to be watched!</h1>
```

2021-03-03 02:50 UTC, reginawang99 commented on src/components/styles/YouTube.scss
> +    background-size: 56%;
it looks like this on my computer! (prob cuz my resolution is lower)
![image](https://user-images.githubusercontent.com/29292203/109742564-1bf6f100-7b84-11eb-97d5-f503e71bec9b.png)
maybe `background-size: contain` would be good!
```suggestion
    background-size: contain;
    padding: 10px 0px;
    background-origin: content-box;
```
the padding pads up and down 10px, and background-origin makes it so the background image is padded also!

2021-03-03 02:50 UTC, reginawang99 commented on src/components/Youtube.tsx
> +                <div id={"computer"}>
hm tbh 4 doesnt really fit on my screen as is rn, thoughts on cutting down to 3 and making it one line OR making it smaller? (this is what it looks like rn after change from below!)

![image](https://user-images.githubusercontent.com/29292203/109744551-5c0ba300-7b87-11eb-96d9-aa33280c0fcc.png)

2021-03-03 02:50 UTC, reginawang99 commented on src/components/Home.tsx
> +        </Carousel> : <YouTube chosenVideo= { chosenVideoPath } setVideo= { chooseVideo } showNext = { toggleCarousel } /> }
nit (not important, feel free to dismiss), i think its easier to read if its cleanly divided on a new line!
```suggestion
        </Carousel> : 
        <YouTube chosenVideo= { chosenVideoPath } setVideo= { chooseVideo } showNext = { toggleCarousel } /> }
```

2021-03-04 07:49 UTC, Phreakester commented on src/components/Youtube.tsx
> +                <div id={"computer"}>
I tried playing around with it for a little bit and I agree that 3 videos should be good!

2021-03-24 00:27 UTC, arjunr00 commented
Sorry for not getting back to this earlier. Is this PR still active or is it on hold?

2021-03-28 01:11 UTC, BryanPan342 requested changes
Really close to giving this an approve! Just a little more :)

2021-03-28 01:11 UTC, BryanPan342 commented on src/components/App.tsx
> +import Home from './Home/index.tsx';
```suggestion
import Home from './Home';
```

2021-03-28 01:11 UTC, BryanPan342 commented on src/components/shared/Youtube.tsx
> +  if (props.chosenVideo == null) {
```suggestion
  if (!props.chosenVideo) {
```

2021-03-28 01:11 UTC, BryanPan342 commented on src/components/shared/Youtube.tsx
> +            <button onClick={() => { props.showNext(true); props.setVideo(chill_girl); }} className={'youtube-video'}>
Make the onclick a function s.t. you can do something like

```
onClick={handleClick(chill_girl)}
```

2021-03-28 01:11 UTC, BryanPan342 commented on src/components/shared/Carousel.tsx
> +  redirect: any;
```suggestion
  redirect: () => void;
```

or better yet, find the React.Dispatch type for this

2021-03-28 01:11 UTC, BryanPan342 commented on src/components/shared/Carousel.tsx
> +                (props.redirect == false && slideIdx === props.children.length - 1))
if props.redirect is going to be a required value, when is this ever false?

2021-03-28 01:11 UTC, BryanPan342 commented on src/components/shared/Carousel.tsx
> +            onClick={(slideIdx === props.children.length - 1 && props.redirect)
same as above.. when is props.redirect not valid?

2021-03-28 04:11 UTC, reginawang99 requested changes
it looks a bit funky on my computer, but i realize that its hard to know cuz we have different computers! lmk if these work on yours :)

2021-03-28 04:11 UTC, reginawang99 commented on src/components/styles/YouTube.scss
> +  justify-content: center;
content should be on top?
```suggestion
```

2021-03-28 04:11 UTC, reginawang99 commented on src/components/styles/YouTube.scss
> +  margin: 0;
some margin might look better?
```suggestion
  margin: 4px;
```

2021-03-28 04:11 UTC, reginawang99 commented on src/components/styles/YouTube.scss
> +  width: 100%;
it runs off the screen for me :( does this work for you? since this has a background image, it might be best to make the object have width/height ratio same as the svg
```suggestion
  height: calc(45vw * 15/23);
  width: 45vw;
```

2021-03-28 04:11 UTC, reginawang99 commented on src/components/styles/YouTube.scss
> +  width: 50%;
since we changed youtube computer, change youtube wrapper accordingly
```suggestion
  margin-left: 3vw;
  margin-right: 3vw;
  width: 100%;
```

2021-03-28 04:11 UTC, reginawang99 commented on src/components/styles/YouTube.scss
> +  width: 40%;
since we changed youtube computer, change youtube wrapper accordingly
```suggestion
```

2021-03-28 06:59 UTC, Phreakester commented on src/components/shared/Carousel.tsx
> +                (props.redirect == false && slideIdx === props.children.length - 1))
Ok, I thought there would be instances where we would use the Carousel but not want to redirect away afterwards so I wanted it to preserve the old behavior when no redirect is given.

2021-03-28 09:15 UTC, Phreakester commented on src/components/shared/Youtube.tsx
> +import React from 'react';
Do you mean the home folder? I agree as its not likely to be used elsewhere.

2021-03-28 09:29 UTC, Phreakester commented on src/components/shared/Carousel.tsx
> +  redirect: any;
Ok, I set it to void right now but ill look into the Dispatch type!

2021-03-28 09:31 UTC, Phreakester commented
Ok, the changes look a little small for me but it seems like it will work better on a wider range of screens so we will go with that!

2021-03-28 12:22 UTC, reginawang99 commented on src/components/shared/Youtube.tsx
> +import React from 'react';
ya

2021-03-28 17:58 UTC, BryanPan342 commented on src/components/shared/Carousel.tsx
> +                (props.redirect == false && slideIdx === props.children.length - 1))
if thats the case lets add the `?` to the redirect prop in CarouselProps!

2021-03-29 16:34 UTC, reginawang99 requested changes
i didnt highlight all changes, please propagate the changes requested! after that, itll be good to go from me :)

2021-03-29 18:35 UTC, reginawang99 approved these changes
nice looks good to me! oo its your first pr for playnet, congrats :)

2021-03-29 18:46 UTC, merged