Prelimilary splitting of sections
uclaacm/Playnet pull request #4
Opened 2021-01-18 05:15 UTC by reginawang99

Add routing to Intro, Activities, Feedback
Add routing to Activities page to Activity1, Activity2, Activity3
Add Base, with Header and Footer + links to intro, activity, and feedback

2021-01-18 18:39 UTC, BryanPan342 requested changes
mostly just some maintenance changes!

i think we should right down where some of the layout within [DESIGN_GUIDELINES](DESIGN_GUIDELINES.md) just so that everything is documented and consistent! But if you think this might be too much I'm not that invested in proposition

2021-01-18 18:39 UTC, BryanPan342 commented on src/index.tsx
> +    </Router>
Can we move this to `App.tsx`? I think components should stay within the same folder (i.e. the purpose of `index.tsx` is for globals and ContextProviders

2021-01-18 18:39 UTC, BryanPan342 commented on src/components/shared/PlaynetConstants.tsx
> +export { HeaderSections };
```suggestion
export enum HeaderSections {
  INTRO = 'intro',
  ACTIVITIES = 'activities',
  FEEDBACK = 'feedback',
}
```

nit: make enum fields caps because they are global

2021-01-18 18:39 UTC, BryanPan342 commented on src/components/shared/Header.tsx
> +
remove double empty line
```suggestion
```

2021-01-18 18:39 UTC, BryanPan342 commented on src/components/shared/Header.tsx
> +}
```suggestion
export interface HeaderProps = {
  section: HeaderSections,
}
```

2021-01-18 18:39 UTC, BryanPan342 commented on src/components/shared/Header.tsx
> +import '../styles/App.scss';
i think these should have their own scss file?

2021-01-18 18:39 UTC, BryanPan342 commented on src/components/shared/Footer.tsx
> +import '../styles/App.scss';
see comment below for separate scss files

2021-01-18 18:39 UTC, BryanPan342 commented on src/components/shared/Base.tsx
> +import '../styles/App.scss';
see comment below for separate scss files

2021-01-18 18:39 UTC, BryanPan342 commented on src/components/Home.tsx
> +import './styles/App.scss';
see comment below for separate scss files

2021-01-18 18:39 UTC, BryanPan342 commented on src/components/Activities/Activity1.tsx
> +import '../styles/App.scss';
see comment below for separate scss files

2021-01-18 18:39 UTC, BryanPan342 commented on src/components/Activities/Activity2.tsx
> +import '../styles/App.scss';
see comment below for separate scss files

2021-01-18 18:39 UTC, BryanPan342 commented on src/components/Activities/Activity3.tsx
> +import '../styles/App.scss';
see comment below for separate scss files

2021-01-18 18:39 UTC, BryanPan342 commented on src/components/shared/Base.tsx
> +}
```suggestion
export interface BaseProps = {
  section: HeaderSections,
  children?: React.ReactNode;
}
```

2021-01-19 06:34 UTC, reginawang99 commented
yee i think we should follow the guidelines. i think it'll be esp nice for the new devs to try it out!

2021-01-19 06:58 UTC, reginawang99 reviewed
addressed!

2021-01-19 06:59 UTC, malsf21 commented on src/components/styles/Activities.scss
> +div {
AFAIK these styles aren't component-local, so this `div` selector is applied globally. It might be worth creating a class for this instead!

2021-01-19 07:00 UTC, malsf21 commented on src/components/Activities.tsx
> +      <Base section={HeaderSections.ACTIVITIES}>
I'm a bit behind-the-times on the new changes to `react-router`, but what are the pros / cons of having one localized `<Switch>` (e.g. everything in `App.tsx`) versus this approach (splitting them up)? Feel free to dismiss this if it isn't relevant haha!

2021-01-19 07:03 UTC, reginawang99 commented on src/components/Activities.tsx
> +      <Base section={HeaderSections.ACTIVITIES}>
it's split up because later we will be adding styles and stuff to this page! this is just a super barebones split just to start up dev work :)

2021-01-19 07:05 UTC, reginawang99 commented on src/components/styles/Activities.scss
> +div {
oh yee makes sense--ill just remove the things inside of the new scss files since they pretty irrelevant for now

2021-01-19 08:31 UTC, reginawang99 commented on src/components/Activities.tsx
> +      <Base section={HeaderSections.ACTIVITIES}>
i think its somewhat standard to take nested routes and put it in a separate area ==> easier to read (functions at one level of abstraction). 

While there are some slight benefits of putting it all into one switch, since we would have urls "activity/1" "activity/2" "activity/3" and "activity" all in one place ==> no double route, I'm not sure that it's that much of a speed up and worth it over ^^

it seems like by  https://reactrouter.com/web/guides/philosophy and a few other sites, the double route seems to be used while nesting so I wouldn't think it's too much of a slow down?  

but also thanks for point that out--i noticed ppl did route matching rather than hard coding it so i changed some stuffs :)

2021-01-19 18:08 UTC, BryanPan342 approved these changes
LGTM 🥳

2021-01-19 18:09 UTC, merged