feat: Activity 2 Compression game
uclaacm/Playnet pull request #45
Opened 2021-03-20 23:35 UTC by darren2hang

- Made Compressed and Uncompressed versions of the Game for Activity 2
- I modified some of the Activity 1 game code to also fit my Game

2021-03-21 19:29 UTC, reginawang99 requested changes
just some suggestions to make it a bit easier to read, but it looks good overall! there are a few other things I might want to take another look at after you resolve these :)

2021-03-21 19:29 UTC, reginawang99 commented on src/components/styles/Activity2.scss
> +}
Maybe we can remove these and make `grid-row-start` and `grid-column-start` inline css?

2021-03-21 19:29 UTC, reginawang99 commented on src/components/Activities/Activity2/index.tsx
> +        <div className='row4-col1 grid-label bottom-left-corner'>Elephant Wearing Hat and Shoes</div>
See below also, but maybe we can do inline css for grid row and column stuffs? cuz it got a bit messy in the css side, and also it’s probably easier to read as well

2021-03-21 19:29 UTC, reginawang99 commented on src/components/Activities/Activity2/index.tsx
> +import ElephantGIF from '../../../assets/activity2/game/elephant.gif';
Vscode probs gets a bit angy abt this—we could add a custom typing like https://github.com/uclaacm/Playnet/tree/main/custom_typing/import-svg to make it chill out

2021-03-21 19:29 UTC, reginawang99 commented on src/components/Activities/Activity2/Game/GamePage.tsx
> +interface GamePageProps {
I’ll probably take a look at this next review, but this might be a bit too many parameters and there might be better form, probably be good to group related parameters into objects, but I’ll take a closer look after you resolve these things :)

2021-03-22 21:17 UTC, darren2hang commented on src/components/Activities/Activity2/Game/GamePage.tsx
> +import { SlideBoxStyles, AnswerDisplayStyles } from '../../../shared/PlaynetConstants';
Yep! i forgot lol

2021-03-22 21:31 UTC, darren2hang commented on src/components/Activities/Activity1/Game2/components/SlideBox.tsx
>  import React, { useState, useEffect } from 'react';
ok!

2021-03-22 21:35 UTC, darren2hang commented on src/components/Activities/Activity2/Game/GamePage.tsx
> +function GamePage(props: GamePageProps): JSX.Element {
Ok! I renamed it.

2021-03-22 21:35 UTC, darren2hang commented on src/components/styles/_variables.scss
> +$mobile-width: 768px;
Ok, i just thought it made it look better.

2021-03-23 18:46 UTC, darren2hang commented on src/components/Activities/Activity2/index.tsx
> +  const [gameTimes, setGameTimes] = useState<number[]>([-1, -1, -1, -1,-1,-1]);
Ok i implemented the session storage. Let me know if I did it correctly.

2021-03-23 18:47 UTC, darren2hang commented on src/components/Activities/Activity2/Game/index.tsx
> +  slides: Record<string, unknown>[];  //each object should have a list of choices, a gif, and
Should I also change the FillInTHeBlankGamePage to use the GamePageComponents interface? Or is it fine since all the FillInTheGamePage props are already typed.

2021-03-23 18:51 UTC, darren2hang commented on src/components/Activities/Activity2/index.tsx
> +import ElephantGIF from '../../../assets/activity2/game/elephant.gif';
I did this. Let me know if I did it correctly. I think it worked but not 100% sure.

2021-03-23 18:52 UTC, darren2hang commented on src/components/styles/Activity2.scss
> +}
oh, i thought inline css should be avoided when possible?

2021-03-23 19:05 UTC, BryanPan342 commented on src/components/Activities/Activity2/index.tsx
> +        <div className='row4-col1 grid-label bottom-left-corner'>Elephant Wearing Hat and Shoes</div>
U could also make this a matrix and pass in the inline css that way.. since all u really care about would be the index of the row or col!

2021-03-23 19:27 UTC, darren2hang commented on src/components/Activities/Activity1/Game2/components/SlideBox.tsx
> +  imgSrc?: string;
i was creating some bugs when i tried changing it to JSX.Element, so I didnt change it.

2021-03-23 19:27 UTC, darren2hang commented on src/components/styles/Activity2.scss
> +}
i still changed it to inline css though.

2021-03-24 00:11 UTC, BryanPan342 reviewed
Only have one real comment to add!

2021-03-24 00:46 UTC, reginawang99 commented on src/components/shared/AnswerChoiceBox.tsx
> +  handleClickAndReturnIsCorrect: () => boolean;
oof this was my rec LOL 😅 it was handleClick originally, but it also is expected to return whether the answer is correct. so I thought It was misleading to just be called handleClick when it does other things, since I’m thinking its not ideal to have to read all the code to know how to use something? What do u think?

2021-03-24 02:59 UTC, reginawang99 commented on src/components/Activities/Activity2/index.tsx
> +import ElephantGIF from '../../../assets/activity2/game/elephant.gif';
yup, my vscode is no longer amgy

2021-03-24 03:10 UTC, reginawang99 commented on src/components/Activities/Activity1/Game2/components/SlideBox.tsx
> +  imgSrc?: string;
yee no worries, theres like a few files that might need to be changed to do this

2021-03-24 03:13 UTC, reginawang99 commented on src/components/styles/Activity2.scss
> +}
i think it should be avoided, but having css in a seperate file, with a lot of extra lines that is basically the same as inline css might bloat the code a bit! i think a lot of like clean code standards are a bit ambigious/weighing pros&cons/opinions on whats most important

2021-03-24 04:17 UTC, reginawang99 requested changes
i think this is all i got and id be happy with merging after this!

2021-03-24 04:17 UTC, reginawang99 commented on src/components/Activities/Activity2/index.tsx
> +      if (storage.getItem(String(index)) === null) {
^
```suggestion
      if (storage.getItem("A2MinigameIndex" + String(index)) === null) {
```

2021-03-24 04:17 UTC, reginawang99 commented on src/components/Activities/Activity2/index.tsx
> +        const time = storage.getItem(String(i));
^
```suggestion
        const time = storage.getItem("A2MinigameIndex" + String(i));
```

2021-03-24 04:17 UTC, reginawang99 commented on src/components/Activities/Activity2/index.tsx
> +import ElephantShoesUncompressedGIF from '../../../assets/activity2/game/elephant_shoe_uncompressed.gif';
i think for the uncompressed gif, it loops rather than just stopping at the end! we can use https://ezgif.com/loop-count for now to make it not loop (loop = 1). (not super important, but its a really quick fix)

i think in the future (or if you want to now, that would be amazing), we should create a `GIFPlayer` component that is passed a list of gifs and times for the gifs and plays them in succession. this helps decrease file size since the user wont have to download same piece of gif twice

2021-03-24 04:17 UTC, reginawang99 commented on src/components/Activities/Activity2/index.tsx
> +  const [gameTimes, setGameTimes] = useState<number[]>([-1, -1, -1, -1,-1,-1]);
ya looks good to me :) just a nit about naming + possible future conflicts

2021-03-24 04:17 UTC, reginawang99 commented on src/components/Activities/Activity2/Game/index.tsx
> +  slides: Record<string, unknown>[];  //each object should have a list of choices, a gif, and
yup, sounds good to me

2021-03-24 19:21 UTC, darren2hang commented on src/components/Activities/Activity2/index.tsx
> +  };
i applied this myself because github wasn't letting me apply from your comment.

2021-03-24 19:26 UTC, darren2hang commented on src/components/Activities/Activity2/Game/FillInBlankGamePage.tsx
> +  const [chosenIncorrectChoices, setIncorrect] = useState<boolean[]>([]);
ok i fixed this. I think i just did this cuz i wasn't really paying attention.

2021-03-24 19:28 UTC, darren2hang commented on src/components/Activities/Activity2/Game/index.tsx
> +}
sorry, i'm a little confused on what you mean by using this in FillInBlankGamePage? Bcuz I do use it in FillInBlankGamePage. The Game class just passes this info to the FIllInBlankGamePage.

2021-03-24 20:04 UTC, darren2hang commented on src/components/Activities/Activity2/index.tsx
> +import ElephantShoesUncompressedGIF from '../../../assets/activity2/game/elephant_shoe_uncompressed.gif';
i fixed the loop. For the gif player would we just get the times by manually finding it or is there a property or something that you can use to get the length or when the gif ends?

2021-03-24 20:19 UTC, reginawang99 commented on src/components/Activities/Activity2/index.tsx
> +import ElephantShoesUncompressedGIF from '../../../assets/activity2/game/elephant_shoe_uncompressed.gif';
probably manully input a time actually

2021-03-24 20:22 UTC, reginawang99 commented on src/components/Activities/Activity2/Game/index.tsx
> +}
i think before, you had a comment/question about whether you should use `CompressionGamePageComponents` in FillInBlankGamePage, rather than splitting it up and passing info. i was just recommending passing `CompressionGamePageComponents` rather than passing the info seperately

2021-03-24 22:31 UTC, darren2hang commented on src/components/Activities/Activity2/Game/index.tsx
> +}
I think I did it. Let me know if I did it correctly.

2021-03-25 09:50 UTC, darren2hang commented on src/components/Activities/Activity2/index.tsx
> +import ElephantShoesUncompressedGIF from '../../../assets/activity2/game/elephant_shoe_uncompressed.gif';
i think i implemented the gif player correctly. I noticed that the image shrinks to nothing for a tiny bit of time as the GIFPlayer switches between gifs.

2021-03-25 11:39 UTC, reginawang99 reviewed
i’m on my phone, so i didn’t get to test these myself, but they basically mostly nits and i’m down to approve (esp since we probs want to apply the new gifs sometime soon, and we can modify code again then). i didn’t know u wanted to change anything tho so lmk when u ready to approve!

2021-03-25 11:39 UTC, reginawang99 commented on src/components/Activities/Activity2/index.tsx
> +      gif: <GIFPlayer gifs={[{path: ElephantGIF, duration: elephantGifTime, id: 'elephant1'}, {path: ElephantHatGIF, duration: elephantHatGifTime, id: 'hat0'}]} alt='Gif of Elephant with Hat being Dr
idt you need to give every gif an index if you are giving the gifplayer an index? could be wrong tho

2021-03-25 11:39 UTC, reginawang99 commented on src/components/Activities/Activity2/index.tsx
> +  const elephantHatGifTime = 6000;
nit: i would probably have the pair of path and time here, and then just pass it directly to component without having to pass info individually, esp if id doesn’t need to be specified on the gif level

2021-03-25 11:39 UTC, reginawang99 commented on src/components/shared/GIFPlayer.tsx
> +    }, props.gifs[index].duration);
nit: maybe also clearTimeout when component dismounts

2021-03-25 11:39 UTC, reginawang99 commented on src/components/shared/GIFPlayer.tsx
> +  id: string;
maybe just setting gifplayer id from Activity2.tsx would be enough?

2021-03-25 11:39 UTC, reginawang99 commented on src/components/shared/GIFPlayer.tsx
> +  let lastTimeout: NodeJS.Timeout;
useref to save reference more robustly

2021-03-25 11:39 UTC, reginawang99 commented on src/components/shared/GIFPlayer.tsx
> +    <img src={props.gifs[index].path + '?'+ String(Date.now())} alt={props.alt+props.id} key={props.id + props.gifs[index].id}/>
just wondering why Date.now is here?

2021-03-25 18:20 UTC, darren2hang commented on src/components/shared/GIFPlayer.tsx
> +    <img src={props.gifs[index].path + '?'+ String(Date.now())} alt={props.alt+props.id} key={props.id + props.gifs[index].id}/>
React would see that the elephantgif would be the same path 2 times in a row. So even if the key changes the gif wouldn't reload. I was stackoverflowing solutions, so this might not be the best way.

2021-03-25 18:24 UTC, darren2hang commented on src/components/Activities/Activity2/index.tsx
> +      gif: <GIFPlayer gifs={[{path: ElephantGIF, duration: elephantGifTime, id: 'elephant1'}, {path: ElephantHatGIF, duration: elephantHatGifTime, id: 'hat0'}]} alt='Gif of Elephant with Hat being Dr
yea, your right.

2021-03-25 18:28 UTC, darren2hang commented on src/components/shared/GIFPlayer.tsx
> +  id: string;
yep, you're right!

2021-03-25 18:35 UTC, darren2hang commented on src/components/Activities/Activity2/index.tsx
> +  const elephantHatGifTime = 6000;
ok

2021-03-25 18:52 UTC, darren2hang commented on src/components/shared/GIFPlayer.tsx
> +    }, props.gifs[index].duration);
I think I added it, but I don't really see why we need to clear the timeout after it finished running.

2021-03-25 19:10 UTC, darren2hang commented on src/components/shared/GIFPlayer.tsx
> +  let lastTimeout: NodeJS.Timeout;
ok, i think i added useRef, but I've never used it before. Let me know if I used it correctly.

2021-03-25 19:17 UTC, BryanPan342 commented on src/components/shared/GIFPlayer.tsx
> +    }, props.gifs[index].duration);
The return is happening when the component is dismounting, meaning when the component is removed from the DOM, we should destroy certain properties that don't exist anymore!

If you have taken CS 32, this is similar to having a destructor. In this case, we wont really lose memory, bc javascript has a garbage collector, but its good practice to do so and sometimes it matters on refreshes and what not

2021-03-25 19:43 UTC, reginawang99 submitted a review, later dismissed
lgtm!! 🎈  
as for 
> i think i implemented the gif player correctly. I noticed that the image shrinks to nothing for a tiny bit of time as the GIFPlayer switches between gifs.

when we get the actual gifs, we can set GIFPlayer height and width to be fixed per game or something

2021-03-25 22:34 UTC, reginawang99 approved these changes

2021-03-25 22:35 UTC, merged

2021-03-26 05:16 UTC, darren2hang commented on src/components/shared/GIFPlayer.tsx
> +    }, props.gifs[index].duration);
thanks! That makes sense.