feat: Activity 1 Cipher Game
uclaacm/Playnet pull request #54
Opened 2021-03-27 03:59 UTC by tr89on

<ul>
<li>added base implementation for cipher game</li>
</ul>

<a href="">Link</a> to activity 1 (click past intro slides)

Closes #13

2021-03-27 08:19 UTC, reginawang99 reviewed
thoughts on removing duplication/not removing duplication @BryanPan342? its ok ill figure it out haha

2021-03-27 08:19 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameSlide.tsx
> +import React from 'react';
this is almost an exact replica of [GameSlide](https://github.com/uclaacm/Playnet/blob/main/src/components/Activities/Activity1/Game2/components/GameSlide.tsx) with the exception that this doesn't have `textIncorrect` or the left part of the gamebox (the alien with a translator). 
im thinking that we should probably decrease duplication and i can think of a few ways to do it
1) use a `Provider` and split left and right components. passes whether incorrect or correct from right to left
- (might be overkill and harder to implement+only 2 games anyways?)
2) make the left image in `GameSlide` optional and just use `GameSlide` instead of this file 
- (but then `alienState` in GameSlide completely useless)
3) pass state from left to right since no props are chained anyways 
- (but might be annoying because it requires a parent of both left and right)

what do you think? or should we just leave it and clean it up later?

2021-03-27 08:19 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/index.tsx
> +  const handleAlienState = (state: ALIEN_STATE, cb?: () => void) => {
same as before duplicate

2021-03-28 11:55 UTC, reginawang99 requested changes
sorry shouldve made the code flow more clear and checked in with you to make sure that we were on the same page. these are logistical things to change. ive also made the images for the other 2 cards for now

2021-03-28 11:55 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +  const HASH_VAL = 5;
we can probably use some sort of sessionid to hash in the future but this is good also

2021-03-28 11:55 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/index.tsx
> +  const rounds = [
if this isn't too much work, lets making it like this psuedocode
round 1, learn the basic cards
```
while (score < 100) {
  const cards = ['APPLE', 'CAR', 'UFO', 'LEMON'];
  const first = cards.pop(Math.random*cards.length - 1) // after this, length should be 3
  const second = cards.pop(Math.random*cards.length - 1) // after this, length should be 2
  const third = cards.pop(Math.random*cards.length - 1)
  runCard(first, second. third);
}
```
round 2. learn the numbers
```
runYayYouGotStar();
score = 0;
while (score < 100) {
  const cards = ['ONE APPLE', 'TWO APPLE', "THREE APPLE"];
  const first = cards.pop(Math.random*cards.length - 1) // after this, length should be 2
  const second = cards.pop(Math.random*cards.length - 1) // after this, length should be 1
  const third = cards.pop(Math.random*cards.length - 1)
  runCard(first, second. third);
}
```
round 3.  combine number and cards.
```
runYayYouGotStar();
score = 0;
while (score < 100) {
  const cards = ['APPLE', 'CAR', 'UFO', 'LEMON' => map apply to become ONE APPLE, TWO APPLE, THREE APPLE, ONE CAR ......
  const first = cards.pop(Math.random*cards.length - 1) // after this, length should be 11
  const second = cards.pop(Math.random*cards.length - 1) // after this, length should be 10
  const third = cards.pop(Math.random*cards.length - 1) 
  runCard(first, second. third);
}
```

2021-03-28 11:55 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/index.tsx
> +  const rounds = [
you can convert ONE APPLE to APPLE, TWO APPLE to TWO-APPLE, THREE APPLE to THREE-APPLE, etc and apply css background image like this:
https://github.com/uclaacm/Playnet/blob/main/src/components/styles/Activities.scss#L55-L65
https://github.com/uclaacm/Playnet/blob/main/src/components/Activities.tsx#L40

2021-03-28 12:22 UTC, reginawang99 reviewed
these are ideas for you! just nice to haves -> remove duplication + practice cleaner code. 

also completely brain vomit suggestions and i mightve missed some things given the time, so keep that in mind. these are just ideas and what i would do to clean this up

2021-03-28 12:22 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameSlide.tsx
> +import React from 'react';
this thread will be referred as ***
```
lots of duplciation in game 1 and game 2 of activity1. i would recommend having a 

"right side of game" component // can be used by both g1 and g2
and
"left side of game" component // g2 maybe component => image with text bubble (you can prob throw this into a SharedGameComponents file or something)
                             // g1 might be able to use g2's component + add the top start and the bottom bar
and a
Component that passes info from left to right  // g1 CipherGameController component
                                               //g2 AmbiguousGameController component
```

2021-03-28 12:22 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameSlide.tsx
> +import React from 'react';
info needed might be
- correct/incorrect
- score
- shouldContinueOnWrong

right side is passed setIsCorrect and setScore  and setTimeChanged
left side is passed the states that the right side set

2021-03-28 12:22 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +  // -----ALIEN HANDLERS------
this duplication should be removed and put into the left component 
see ***

2021-03-28 12:22 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/ProgressBar.tsx
> +  const containerStyles ={
why is everything inline? throw into a css file and only have line 20 be inline css

2021-03-28 12:22 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/index.tsx
> +import Apple from '../../../../assets/activity1/apple.svg';
these imports can all just be background images and like this https://github.com/uclaacm/Playnet/blob/main/src/components/styles/Activities.scss#L55-L65

2021-03-28 12:22 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +  const [MAX_HAPPINESS, CORRECT_PTS, INCORRECT_PTS] = [100, 20, 10];
throw this line into the PlaynetConstants file and make sure to comment that its for a1g1

2021-03-28 12:22 UTC, reginawang99 commented on src/components/Activities/Activity1/index.tsx
> +      <div className="game-intro">
i saw we have 3 of these which are basically the same minus the text. we can standardize this and throw into a shared file of GameComponents or something

2021-03-28 18:17 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game1/index.tsx
> +  const rounds = [
If i may add in:

A suggestion would be to have something like the following:

```js
const items = ['APPLE', 'CAR', 'UFO', 'LEMON'];
const nums = ['ONE', 'TWO', 'THREE'];
const nums_and_items = nums.reduce((n_acc, n_v) => {
  const num_and_items = items.reduce((i_acc, i_v) => [...i_acc, `${n_v} ${i_v}`], []);
  return [...n_acc, ...num_and_items];
}, []);
```

From here you have your three levels!

```
const LEVELS = [items, nums, nums_and_items];
```

You can then create a mapping between a word and the corresponding image!

2021-03-28 23:35 UTC, tr89on commented on src/components/Activities/Activity1/index.tsx
> +      <div className="game-intro">
Yee thats what I was thinking earlier with having an intro/transition slide component

2021-03-28 23:36 UTC, tr89on commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +  const [MAX_HAPPINESS, CORRECT_PTS, INCORRECT_PTS] = [100, 20, 10];
![Screen Shot 2021-03-28 at 4 35 34 PM](https://user-images.githubusercontent.com/22901219/112772053-a0059280-8fe3-11eb-8f87-87bcc59033f3.png)

Is there a way to import the constants as a single array instead of doing this?

2021-03-28 23:37 UTC, tr89on commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +  const [MAX_HAPPINESS, CORRECT_PTS, INCORRECT_PTS] = [100, 20, 10];
Yep, got it!

2021-03-28 23:37 UTC, tr89on commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +  const HASH_VAL = 5;
Oh cool makes sense! Is there a typical way people get sessionId? (like through cookies vs location)

2021-03-28 23:39 UTC, tr89on commented on src/components/Activities/Activity1/Game1/index.tsx
> +  const rounds = [
Oh I see so each word would be linked to its background image through the css class/id instead of manually putting them together, makes sense. Just to be clarify, would this mean having separate ids for 'APPLE' and 'TWO-APPLE' that correspond to their images? @reginawang99

2021-03-28 23:39 UTC, tr89on commented on src/components/Activities/Activity1/Game1/index.tsx
> +  const rounds = [
@BryanPan342 woah thats a cool reducer 😮  thanks for the suggestion!

2021-03-29 03:24 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/index.tsx
> +  const rounds = [
yup! hopefully that would make it easier

2021-03-30 07:34 UTC, reginawang99 reviewed
just a bunch of nits! looks sleek 👌 im down to approve, lmk

2021-03-30 07:34 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +      const handler = newHappiness === MAX_HAPPINESS ? advanceGame : () => {return;}; // prevent no-op by finishing animation before scene change
nit: i think its a bit easier to remember the card if you see it on the screen a bit?
```suggestion
      const handler = newHappiness === MAX_HAPPINESS ? advanceGame : () => nextSlide(); // prevent no-op by finishing animation before scene change
```

2021-03-30 07:34 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +      handleAlienState(ALIEN_STATE.ANGER);
^^
```suggestion
      handleAlienState(ALIEN_STATE.ANGER, ()=>nextSlide());
```

2021-03-30 07:34 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +    nextSlide();
^^
```suggestion
```

2021-03-30 07:34 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameSlide.tsx
> +      <AnswerChoiceBox handleClickAndReturnIsCorrect={()=>handleClick(1)} imgSrc={''} backgroundImg={card1.split(' ').join('-')}/>
```suggestion
      <AnswerChoiceBox handleClickAndReturnIsCorrect={()=>handleClick(1)} id={card1.split(' ').join('-')}/>
```

2021-03-30 07:34 UTC, reginawang99 commented on src/components/shared/AnswerChoiceBox.tsx
> +  backgroundImg?: string;
maybe called id instead?
```suggestion
  id?: string;
```

2021-03-30 07:34 UTC, reginawang99 commented on src/components/shared/AnswerChoiceBox.tsx
> +  const {imgSrc, backgroundImg} = props;
```suggestion
  const {imgSrc, id, text} = props;
```

2021-03-30 07:34 UTC, reginawang99 commented on src/components/shared/AnswerChoiceBox.tsx
> +      {imgSrc !== undefined ? <img src={imgSrc}/> : <span>{props.text}</span>}
```suggestion
      {imgSrc && <img src={imgSrc}/>}
      {text && <span>{props.text}</span>}
```

2021-03-30 07:34 UTC, reginawang99 commented on src/components/shared/PlaynetConstants.ts
> +export enum Activity1Game1Values {
https://stackoverflow.com/questions/4709175/what-are-enums-and-why-are-they-useful

> You should always use enums when a variable (especially a method parameter) can only take one out of a small set of possible values. Examples would be things like type constants (contract status: "permanent", "temp", "apprentice"), or flags ("execute now", "defer execution").

think of enums of almost like options

2021-03-30 07:34 UTC, reginawang99 commented on src/components/shared/PlaynetConstants.ts
> +export enum Activity1Game1Values {
do this instead
```suggestion
export var Activity1Game1Values = {
  MAX_HAPPINESS: 100,
  CORRECT_PTS: 20,
  INCORRECT_PTS: 10,
}

2021-03-30 07:34 UTC, reginawang99 commented on src/components/shared/TransitionSlide.tsx
> +  const children = props.children && props.children.map((item) => item);
why `props.children.map((item) => item)`? am i wrong about something?

2021-03-30 07:50 UTC, tr89on commented on src/components/shared/TransitionSlide.tsx
> +  const children = props.children && props.children.map((item) => item);
Oh whoops i think i had something else there earlier

2021-03-30 17:44 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameSlide.tsx
> +      <AnswerChoiceBox handleClickAndReturnIsCorrect={()=>handleClick(1)} imgSrc={''} id={card1.split(' ').join('-')}/>
nit: its nbd but
```suggestion
      <AnswerChoiceBox handleClickAndReturnIsCorrect={()=>handleClick(0)} id={card0.split(' ').join('-')}/>
      <AnswerChoiceBox handleClickAndReturnIsCorrect={()=>handleClick(1)} id={card1.split(' ').join('-')}/>
```

2021-03-30 17:44 UTC, reginawang99 approved these changes
nice looks good to me!!

2021-03-30 17:44 UTC, merged