refactor: Activity 2 game: add final gifs, remove clock at bottom (3rd attempt)
uclaacm/Playnet pull request #56
Opened 2021-03-27 05:02 UTC by darren2hang

- Add the final gifs for the game (Alien and elephant gifs)
- Remove the clock with time from the bottom of the page, since design said the time would distract the students
closes: #44 

hopefully, this fixed the weird git branch issue.

2021-03-27 06:46 UTC, reginawang99 requested changes
looks good! mainly just some changes that we shouldve maybe addressed before 😅

2021-03-27 06:46 UTC, reginawang99 commented on src/components/Activities/Activity2/Game/FillInBlankGamePage.tsx
>            <span className='details'>
oops shoulda caught this earlier, but you have a css `.scene-info .details` but you don't use it because the details is under `.scene-info .icon .details`
```suggestion
        </div>
        <span className='details'>
```
probs need to delete a `</div>` below as well

2021-03-27 06:46 UTC, reginawang99 commented on src/components/Activities/Activity2/Game/FillInBlankGamePage.tsx
> -  });
not relevant, but bryan recommended having a `}, []);` at the end of a useEffect!

this is to easier see that it is the end of a useEffect and make it easier to add dependencies to the useEffect in the future

2021-03-27 06:46 UTC, reginawang99 commented on src/components/Activities/Activity2/index.tsx
> +      answerDisplayWords: ['alien', 'with', 'flower', 'and', 'blank'],
i know its not in this commit, but do we want to fix up GIFPlayer? what we can do is fix the width and height to something, maybe `xx vmin` or something! that way, when the gifs are being loaded, GIFPlayer will stay same size

2021-03-27 06:46 UTC, reginawang99 commented on src/components/Activities/Activity2/index.tsx
> +import ElephantGIF from '../../../assets/activity2/game/el1.gif';
maybe more descriptive image names would be good?

2021-03-30 01:45 UTC, darren2hang commented on src/components/Activities/Activity2/Game/FillInBlankGamePage.tsx
> -  });
I thought that adding an empty [ ] a the end makes the useEffect only run once. Not entirely sure but I've read that people add [ ] at the end to make a fake constructor for functional components.

2021-03-30 01:47 UTC, darren2hang commented on src/components/Activities/Activity2/Game/FillInBlankGamePage.tsx
>            <span className='details'>
ok I did this. I didn't accept your suggestion bcuz I wanted to do all the necessary changes in one commit

2021-03-30 01:55 UTC, darren2hang commented on src/components/Activities/Activity2/index.tsx
> +      answerDisplayWords: ['alien', 'with', 'flower', 'and', 'blank'],
I applied css to the class surrounding gif player, not actually to gif player. This fixes the page changing size bug. Not sure if you wanted me to apply the css specifically on the gifplayer component. My idea was that its better to just make the container around gif player a fixed width than to always set gif player to a fixed width. As this would allow gif player to be more flexibly sized in the future.

2021-03-30 02:04 UTC, darren2hang commented on src/components/Activities/Activity2/index.tsx
> +import ElephantGIF from '../../../assets/activity2/game/el1.gif';
ok!

2021-03-30 03:06 UTC, reginawang99 commented on src/components/Activities/Activity2/Game/FillInBlankGamePage.tsx
> -  });
oh ya i think you right hmm https://stackoverflow.com/questions/53120972/how-to-call-loading-function-with-react-useeffect-only-once oh wells haha

2021-03-30 03:06 UTC, reginawang99 commented on src/components/Activities/Activity2/index.tsx
> +      answerDisplayWords: ['alien', 'with', 'flower', 'and', 'blank'],
ok, that sounds good to me!

2021-03-30 03:10 UTC, reginawang99 approved these changes
nice, looks good to me!!

2021-03-30 03:11 UTC, merged