fix: bug fix where after refresh, video title screen shows up and hops to middle of carousel
uclaacm/Playnet pull request #65
Opened 2021-03-31 01:17 UTC by reginawang99

- fix bug
- add back button to last screen
- add ENUM for videos for ease of adding intro animation

2021-03-31 20:10 UTC, BryanPan342 requested changes
Two minor changes!

Looks really good :)

2021-03-31 20:10 UTC, BryanPan342 commented on src/components/Home/Youtube.tsx
> +            <p>How to play Minecraft</p>
all of this similar.. can we put this into an array? it will make editing the HTML itself easier!

```
const videos = {
  [VideoChoics.CHILL_GIRL]:  {
    alt: 'Image of a girl with headphones on studying',
    text: 'LoFi hip hop to study to',
  },
  ...
};
```

2021-03-31 20:10 UTC, BryanPan342 commented on src/components/Home/index.tsx
> +    }
```suggestion
    if (!carouselSlide) return;
    video ? setChosenVideo(video as VideoChoices) : storage.removeItem('slideIdx');
```

2021-03-31 23:36 UTC, reginawang99 commented on src/components/Home/index.tsx
> +    return () => storage.removeItem('chosenVideo');
question about these `sessionStorage` keys:

is it ever done where you save these key strings (like `'chosenVideo'`) in a `SessionStorageConstants.ts` file?

2021-04-01 00:59 UTC, BryanPan342 commented on src/components/Home/index.tsx
> +    return () => storage.removeItem('chosenVideo');
honestly i think its fine.. mostly because all of the interactions with storage should be in the context of the same file imo

2021-04-01 01:01 UTC, BryanPan342 approved these changes
LGTM

2021-04-01 01:02 UTC, merged