Autoplay sound btns
uclaacm/Playnet pull request #70
Opened 2021-04-01 18:08 UTC by Phreakester

Closes #42 
Adds buttons for mute and autoplay and puts them next to replay button in carousel. Mute and Autoplay state are saved in session storage. Moves buttons and progress bar to more closely math the figma.

2021-04-02 01:11 UTC, tr89on commented on src/components/Activities/Activity1/Game2/components/GameSlide.tsx
> +  const [playIncorrect] = useSound(IncorrectSFX, { volume: 0.5});
this is a minor thing but to save work looking for playCorrect() and playIncorrect() and adding if statements to each it might be easier to set the sound volume to either 0 or 0.5 at the beginning based on isMuted or something like that

2021-04-02 01:13 UTC, tr89on commented on src/components/shared/Carousel.tsx
> +                        <button className='util-button autoplay-button' onClick={()=>startAutoAdvance()} /> }
it was a little confusing at first to me that the autoplay button becomes completely disabled after being activated instead of being able to toggle autoplay(?)

2021-04-02 02:02 UTC, Phreakester commented on src/components/shared/Carousel.tsx
> +                        <button className='util-button autoplay-button' onClick={()=>startAutoAdvance()} /> }
Yeah that makes sense, just implemented it as a toggle, thanks!

2021-04-02 02:05 UTC, reginawang99 commented on src/components/Activities/Activity1/Game2/components/GameSlide.tsx
> +  const [playIncorrect] = useSound(IncorrectSFX, { volume: 0.5});
^^ agreed

2021-04-02 03:55 UTC, reginawang99 requested changes
looks p good! just some naming confuse and cleaner code

2021-04-02 03:55 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +    if (!isMutedStorage) return;
nit:
```suggestion
    const muted = storage.getItem('isMuted');
    if (!muted) return;
```

2021-04-02 03:55 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +  const [isMuted, setMute] = useState(false);
nit: (and propagate) usually for state variables, you try to do `const [xxx, setXxx] = useState...`
```suggestion
  const [isMuted, setIsMuted] = useState(false);
```

2021-04-02 03:55 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +  const [isAutoAdvance, setAutoAdvance] = useState(false);
state variable see comment right below

(random idea maybe feel free to dismiss, maybe autoplay? dw autoadvance is good too!)

2021-04-02 03:55 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +    if (child.animationTime) {setTimeout(() => goNext(), child.animationTime * 1000);}
maybe use your method `autoAdvance`?

2021-04-02 03:55 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +  function startAutoAdvance(): void {
`enableAutoAdvance` maybe?

2021-04-02 03:55 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +    if (child.animationTime) {setTimeout(() => goNext(), child.animationTime * 1000);}
maybe use your method `autoAdvance`?

2021-04-02 03:55 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +  function stopAutoAdvance(): void {
`disableAutoAdvance` (stop sounds temporary and doesnt sound like configs)

2021-04-02 03:55 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
>                    <span className='time-bar-container'>
wanna stick this on the very top? with css absolute and such  [like this](https://www.figma.com/file/7DzNiScbp6t3x0p86pz5P9/Playnets?node-id=0%3A1)? or next commit works too!

2021-04-02 03:55 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +                    </Tooltip>
you can do something like this! and have css for `sound-off-button` and `sound-on-button`
```suggestion
                    <Tooltip text= {isMuted ? 'Unmute' : 'Mute'}>
                      <button className=`sound-${isMuted ? 'off' : 'on'}-button`  onClick={(()=>handleMutedButtonClick())} />}
                    </Tooltip>
```

2021-04-02 03:55 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +                    </Tooltip>
same with other two

2021-04-02 03:55 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +              ? props.finalButtonHandleClick : () => {goNext(); stopAutoAdvance();}}
autoadvance should probably save across different carousels? idk what do u think

2021-04-02 16:55 UTC, Phreakester commented on src/components/shared/Carousel.tsx
>                    <span className='time-bar-container'>
The progress bar? Yeah I can try and do that here, do we want it to stay at the very top? In the figma it starts at the top and then moves down.

2021-04-02 19:37 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
>                    <span className='time-bar-container'>
this is the right one! https://www.figma.com/file/7DzNiScbp6t3x0p86pz5P9/Playnets?node-id=473%3A18259

we also have another ticket for it tho

2021-04-02 20:21 UTC, Phreakester commented on src/components/shared/Carousel.tsx
>                    <span className='time-bar-container'>
Ok, I will split this up for another PR, so I will mark this as resolved!

2021-04-02 20:52 UTC, Phreakester commented on src/components/shared/Carousel.tsx
> +              ? props.finalButtonHandleClick : () => {goNext(); stopAutoAdvance();}}
I thought that it was a little confusing/too fast if it immediately started going when you got to the next carousel, but we can try it with it saving across the carousels, it is already stored in session storage anyways.

2021-04-02 21:57 UTC, reginawang99 requested changes
minor changes + mute option available in minigame. 

maybe we can absolute the buttons on the top right, and make 
`mute-button` + {animation-time && (`replay-button` + `autoplay-button`)} 
available on every carousel

2021-04-02 21:57 UTC, reginawang99 commented on src/assets/unmute_btn.svg
> +<svg width="45" height="34" viewBox="0 0 45 34" fill="none" xmlns="http://www.w3.org/2000/svg">
i think karen put up new more finalized autoplay + unmute buttons, if we can add those in instead https://www.figma.com/file/7DzNiScbp6t3x0p86pz5P9/Playnets?node-id=508%3A40006

2021-04-02 21:57 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +    if (!isMuted){
```suggestion
    } else
    {
```

2021-04-02 21:57 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +    }
else

2021-04-02 21:57 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +                    <Tooltip text= {isMuted ? 'Unmute' : 'Mute'}>
this shouldn't be in the `time-bar-container` since we'll be moving the time bar. we should leave timebar as is in this commit. 

anyhow it should probably also be available in the minigames so that you can enable or disable sound during gameplay? https://deploy-preview-70--play-net.netlify.app/activities/lost-in-translation

2021-04-02 21:57 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +                      <button className={'util-button ' + (isMuted ? 'unmute-button' : 'mute-button')} onClick={handleMuteButtonClick} />
nit: 
```suggestion
                      <button className={'util-button ' + (isMuted ? 'unmute' : 'mute') + '-button'} onClick={handleMuteButtonClick} />
```

2021-04-02 21:57 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +                      <button className={'util-button autoplay-button-' + (isAutoAdvance ? 'autoplaying' : 'not-autoplaying')} onClick={() => handleAutoplayButtonClick()} />
nit:
```suggestion
                      <button className={'util-button autoplay-button-' + (isAutoAdvance ? 'autoplaying' : 'not-autoplaying')} onClick={handleAutoplayButtonClick} />
```
for replay also

2021-04-02 21:57 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +              ? props.finalButtonHandleClick : () => {goNext(); disableAutoAdvance();}}
we should throw `disableAutoAdvance()` into `goNext()` to reduce clutter

2021-04-03 03:21 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +                    <Tooltip text= {isMuted ? 'Unmute' : 'Mute'}>
don't worry about this, i can do this in another commit

2021-04-03 04:01 UTC, Phreakester commented on src/components/shared/Carousel.tsx
> +              ? props.finalButtonHandleClick : () => {goNext(); disableAutoAdvance();}}
hmmm, but autoAdvance calls goNext whenever it progresses the slides, maybe I can make a function to handle it and reduce clutter?

2021-04-03 04:11 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +              ? props.finalButtonHandleClick : () => {goNext(); disableAutoAdvance();}}
Hm I just realized that this is only run if the button itself was clicked. What were u thinking for this?

2021-04-03 04:16 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +              ? props.finalButtonHandleClick : () => {goNext(); disableAutoAdvance();}}
No this is fine, I think you should throw in ‘disableAutoAdvance’ into the ‘goPrev’ as well then to match! (You can remove from goPrev)

2021-04-03 04:25 UTC, Phreakester commented on src/components/shared/Carousel.tsx
> +              ? props.finalButtonHandleClick : () => {goNext(); disableAutoAdvance();}}
Ok, I changed it, thanks!

2021-04-03 04:26 UTC, Phreakester commented on src/components/shared/Carousel.tsx
> +                    <Tooltip text= {isMuted ? 'Unmute' : 'Mute'}>
Ok, I havent done it yet so I will mark as resolved

2021-04-03 07:49 UTC, reginawang99 reviewed
just a super nitty comment, looks good to me!

2021-04-03 07:49 UTC, reginawang99 commented on src/components/shared/Carousel.tsx
> +
thoughts on throwing all of this (ends with []) into a single useEffect? you can also delimit with comments like
`//set muted`

2021-04-03 08:05 UTC, reginawang99 approved these changes
LGTM!

2021-04-03 08:05 UTC, merged