feat: activity1 game1 extra help if fail too many times
uclaacm/Playnet pull request #76
Opened 2021-04-02 08:52 UTC by reginawang99

- if kid keeps losing `appeasing the alien` too many times, they will start to receive support.
![image](https://user-images.githubusercontent.com/29292203/113399451-1a704280-9355-11eb-8849-44099c2fb263.png)
       - the support is that if they hover over the wrong card, the alien will do a lil frowny face

other
- refactor a1g2 (ambiguous phrases game) so that cards are the same size
- refactor alien so that all states are all the same size
- refactor computer to allow going to back to activities page
- refactor AnswerChoiceBox and handling clicks

oop big boi

2021-04-02 23:29 UTC, BryanPan342 requested changes
a single suggestion

2021-04-02 23:29 UTC, BryanPan342 commented on src/components/Home/FinalSlide.tsx
> +  // TODO: cleanup
is this suppsoed to be here?

maybe letsjust make an issue instead?

2021-04-02 23:29 UTC, BryanPan342 commented on src/components/shared/PlaynetConstants.ts
> +  INCORRECT_PTS: 20,
why not keep this at 10?

2021-04-02 23:29 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +    }
your running setAlienState twice in the case where timeout is false


```suggestion
    if(timeout === false) return;
    alienTimeout.current && clearTimeout(alienTimeout.current);
    alienTimeout.current = setTimeout(() => {
      alienTimeout.current = undefined;
      setAlienState(ALIEN_STATE.BASE);
      cb && cb();
    }, 1000);
```

2021-04-02 23:29 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +    if (roundNum >   THRESHOLD_TO_HELP_PER_GAME ) {
the spacing is throwing me off

2021-04-02 23:29 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +    }
also.. what if we did the check to see if cb is defined?

seems to me that having a callback is deterministic if we should run a timeout?

2021-04-02 23:29 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +  }, [hoverIncorrect]);
nit: i generally try to eliminate nesting where possible, you don't have to change! but just wanted to share what I do

```suggestion
  useEffect(()=>{
    if (roundNum <= THRESHOLD_TO_HELP_PER_GAME) return;
    handleAlienState(hoverIncorrect ? ALIEN_STATE.SAD : ALIEN_STATE.BASE);
  }, [hoverIncorrect]);
```

2021-04-02 23:38 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +    if (roundNum >   THRESHOLD_TO_HELP_PER_GAME ) {
ah oops

2021-04-02 23:40 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +  }, [hoverIncorrect]);
just wondering, why eliminate nesting where possible? is it for like cleanness or easier to read code?

2021-04-03 00:00 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +    }
sure sounds good! we could merge this part of this file with [this other duplicated file](https://github.com/uclaacm/Playnet/blob/cab134e886701690aabcc789f8f357294344397b/src/components/Activities/Activity1/Game2/components/GameSlide.tsx) when we refactor sometime!

2021-04-03 00:03 UTC, reginawang99 commented on src/components/Home/FinalSlide.tsx
> +  // TODO: cleanup
ah this was spillover from last commit. yee i'll make an issue instead

2021-04-03 00:25 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameSlide.tsx
>  interface CipherGameSlideProps {
Not important, but I've been wondering why we do interface rather than type? I know it's in the design guidelines, and interfaces are just basically more powerful types. Though as props, is the extra power useful? or is there another reason?

2021-04-03 01:05 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +    }
yeah we could make it its own hook if we want to!

2021-04-03 01:31 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +  }, [hoverIncorrect]);
its a rule of thumb that leads to cleaner code

I think there are also other optimization when it comes to the V8 engine, but its too big brain for me

2021-04-03 01:31 UTC, BryanPan342 commented on src/components/Activities/Activity1/Game1/components/CipherGameSlide.tsx
>  interface CipherGameSlideProps {
Honestly there is no real reason besides the fact that it allows u to do some nifty stuff with classes once in a while or to extend interfaces..

but tbh the reason I use interfaces over types is bc I learned typescript by using interfaces for more complex relationships

2021-04-03 01:46 UTC, BryanPan342 approved these changes
LGTM :)

2021-04-03 01:47 UTC, merged

2021-04-03 02:03 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +  }, [hoverIncorrect]);
ahh right the loop unrolling stuff from cs33, makes sense ty!

2021-04-03 02:05 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +    }
ooo thats cool ive never done hehe, will try sometime!