feat: make words phonetic for cipher game
uclaacm/Playnet pull request #77
Opened 2021-04-02 09:06 UTC by tr89on

Uses builtin SpeechSynthesis to perform text to speech on ciphered words

Closes #72.

2021-04-02 19:02 UTC, reginawang99 commented
currently looking into this more!

2021-04-02 20:24 UTC, reginawang99 requested changes
cool 😎

2021-04-02 20:24 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +  };
? probably explain or make easier to read

we can probably also use `ascii-values` instead of `ascii-code` as well

2021-04-02 20:24 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +    speechSynthesis.speak(speech);
i dont think this belongs here. maybe make a 
```
useEffect (()=>{
...
}, [slideIdx]);
```

2021-04-02 20:24 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +    const speech = new SpeechSynthesisUtterance(displayScrambledText().toLowerCase());
do we want to use a different and more inviting voice? (another lang works too) https://talkrapp.com/speechSynthesis.html 
```suggestion
    const speech = new SpeechSynthesisUtterance(displayScrambledText().toLowerCase());
    speech.lang = 'de-DE';
```

2021-04-02 20:26 UTC, reginawang99 commented
also, i tried out https://www.npmjs.com/package/typo-js, and while it is better, it makes the computer hella slow cuz it makes the client load the dictionary. so let's not do that probably (unless we have a backend, but i feel like thats way overkill and its good enough rn)

2021-04-02 21:00 UTC, tr89on commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +  };
wait what r ascii-values?

2021-04-03 01:57 UTC, reginawang99 requested changes
last thing then it looks good to me

2021-04-03 01:57 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +    }
if you see for loops, try to think if theres a functional way to do it since it usu ends up with cleaner + less + easier to read code

```suggestion
       const closestVowel = vowels.find((vowel) => charCode <= vowel.charCodeAt(0)) || 'U';
```

2021-04-03 01:57 UTC, reginawang99 commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +    let char = word.toUpperCase().charCodeAt(0);
nit: 
```suggestion
    let charCode = word.toUpperCase().charCodeAt(0);
```

2021-04-03 02:02 UTC, tr89on commented on src/components/Activities/Activity1/Game1/components/CipherGameRound.tsx
> +    }
ok!

2021-04-03 02:32 UTC, reginawang99 approved these changes
LGTM

2021-04-03 02:32 UTC, merged